### ISSUE TITLE
SIGSEGV go-alpm

### ISSUE THREAD

**Issue by rNoz** [Jguer/yay#1204]
#### Affected Version

yay v9.4.6 - libalpm v12.0.1

#### Issue

I get a segmentation fault when trying to install any package.

I tried downgrading the `go` package but it continues failing. I also tried both `yay` and `yay-bin` from AUR.

#### Steps to reproduce

1. Run yay to install a package, e.g. `yay boost`

#### Output

```
$ yay boost
unexpected fault address 0xffffffff
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0xffffffff pc=0x4e2457]

goroutine 1 [running]:
runtime.throw(0x789691, 0x5)
        /usr/lib/go/src/runtime/panic.go:1112 +0x72 fp=0xc000223620 sp=0xc0002235f0 pc=0x439022
runtime.sigpanic()
        /usr/lib/go/src/runtime/signal_unix.go:694 +0x3cc fp=0xc000223650 sp=0xc000223620 pc=0x44ec1c
github.com/Jguer/go-alpm.(*list).forEach(0xffffffff, 0xc000223698, 0xc0002236c0, 0x4e35d5)
        /root/go/pkg/mod/github.com/!jguer/go-alpm@v0.0.0-20191122171459-5cffc6e8fc69/types.go:111 +0x37 fp=0xc000223678 sp=0xc000223650 pc=0x4e2457
github.com/Jguer/go-alpm.PackageList.ForEach(0xffffffff, 0x1719a80, 0xc0002236f0, 0xffffffff, 0x0)
        /root/go/pkg/mod/github.com/!jguer/go-alpm@v0.0.0-20191122171459-5cffc6e8fc69/package.go:48 +0x67 fp=0xc0002236c8 sp=0xc000223678 pc=0x4e1857
github.com/Jguer/go-alpm.PackageList.Slice(0xffffffff, 0x1719a80, 0x1, 0x1, 0xffffffff)
        /root/go/pkg/mod/github.com/!jguer/go-alpm@v0.0.0-20191122171459-5cffc6e8fc69/package.go:56 +0x72 fp=0xc000223728 sp=0xc0002236c8 pc=0x4e18f2
main.queryRepo.func1(0x1719d20, 0x1719a80, 0x4ddf0a, 0x6ea6f0)
        /app/query.go:303 +0x1d7 fp=0xc0002237b0 sp=0xc000223728 pc=0x6e64e7
github.com/Jguer/go-alpm.DBList.ForEach.func1(0x1719d20, 0xc000223820, 0x4e4635)
        /root/go/pkg/mod/github.com/!jguer/go-alpm@v0.0.0-20191122171459-5cffc6e8fc69/db.go:36 +0x38 fp=0xc0002237e0 sp=0xc0002237b0 pc=0x4e2ae8
github.com/Jguer/go-alpm.(*list).forEach(0x1719da0, 0xc000223828, 0x1719a80, 0xc000223848)
        /root/go/pkg/mod/github.com/!jguer/go-alpm@v0.0.0-20191122171459-5cffc6e8fc69/types.go:111 +0x48 fp=0xc000223808 sp=0xc0002237e0 pc=0x4e2468
github.com/Jguer/go-alpm.DBList.ForEach(0x1719da0, 0x1719a80, 0xc000223890, 0x0, 0x0)
        /root/go/pkg/mod/github.com/!jguer/go-alpm@v0.0.0-20191122171459-5cffc6e8fc69/db.go:35 +0x67 fp=0xc000223858 sp=0xc000223808 pc=0x4dff17
main.queryRepo(0xc0000990a0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x5e, 0x0)
        /app/query.go:297 +0xd7 fp=0xc0002238c8 sp=0xc000223858 pc=0x6d9537
main.displayNumberMenu(0xc0000990a0, 0x1, 0x1, 0x2, 0x0)
        /app/cmd.go:313 +0x129 fp=0xc000223e48 sp=0xc0002238c8 pc=0x6a0cd9
main.handleYogurt(...)
        /app/cmd.go:247
main.handleYay(0x7883c9, 0x1)
        /app/cmd.go:236 +0x179 fp=0xc000223eb0 sp=0xc000223e48 pc=0x6a0349
main.handleCmd(0x0, 0x0)
        /app/cmd.go:169 +0x169 fp=0xc000223f28 sp=0xc000223eb0 pc=0x69f499
main.main()
        /app/main.go:231 +0xeb fp=0xc000223f88 sp=0xc000223f28 pc=0x6c60eb
runtime.main()
        /usr/lib/go/src/runtime/proc.go:203 +0x212 fp=0xc000223fe0 sp=0xc000223f88 pc=0x43b672
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000223fe8 sp=0xc000223fe0 pc=0x4683b1

goroutine 29 [IO wait]:
internal/poll.runtime_pollWait(0x7f03ca3f5d58, 0x72, 0xffffffffffffffff)
        /usr/lib/go/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc00013a218, 0x72, 0x4300, 0x4336, 0xffffffffffffffff)
        /usr/lib/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/lib/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc00013a200, 0xc0005c4000, 0x4336, 0x4336, 0x0, 0x0, 0x0)
        /usr/lib/go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc00013a200, 0xc0005c4000, 0x4336, 0x4336, 0x203000, 0x280, 0x280)
        /usr/lib/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc000010010, 0xc0005c4000, 0x4336, 0x4336, 0x0, 0x0, 0x0)
        /usr/lib/go/src/net/net.go:184 +0x8e
crypto/tls.(*atLeastReader).Read(0xc0000a6180, 0xc0005c4000, 0x4336, 0x4336, 0x400, 0x7f03cb553000, 0xc00011b9c8)
        /usr/lib/go/src/crypto/tls/conn.go:760 +0x60
bytes.(*Buffer).ReadFrom(0xc0000493d8, 0x809e00, 0xc0000a6180, 0x410875, 0x7340e0, 0x775640)
        /usr/lib/go/src/bytes/buffer.go:204 +0xb1
crypto/tls.(*Conn).readFromUntil(0xc000049180, 0x80a0a0, 0xc000010010, 0x5, 0xc000010010, 0x8)
        /usr/lib/go/src/crypto/tls/conn.go:782 +0xec
crypto/tls.(*Conn).readRecordOrCCS(0xc000049180, 0x0, 0x0, 0xc00011bd38)
        /usr/lib/go/src/crypto/tls/conn.go:589 +0x115
crypto/tls.(*Conn).readRecord(...)
        /usr/lib/go/src/crypto/tls/conn.go:557
crypto/tls.(*Conn).Read(0xc000049180, 0xc0004a6000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/go/src/crypto/tls/conn.go:1233 +0x15b
bufio.(*Reader).Read(0xc000492ba0, 0xc00045e498, 0x9, 0x9, 0xc00011bd38, 0x7a8c00, 0x63cbc5)
        /usr/lib/go/src/bufio/bufio.go:226 +0x24f
io.ReadAtLeast(0x809ce0, 0xc000492ba0, 0xc00045e498, 0x9, 0x9, 0x9, 0xc000098030, 0x0, 0x809f40)
        /usr/lib/go/src/io/io.go:310 +0x87
io.ReadFull(...)
        /usr/lib/go/src/io/io.go:329
net/http.http2readFrameHeader(0xc00045e498, 0x9, 0x9, 0x809ce0, 0xc000492ba0, 0x0, 0x0, 0xc00009adb0, 0x0)
        /usr/lib/go/src/net/http/h2_bundle.go:1479 +0x87
net/http.(*http2Framer).ReadFrame(0xc00045e460, 0xc00009adb0, 0x0, 0x0, 0x0)
        /usr/lib/go/src/net/http/h2_bundle.go:1737 +0xa1
net/http.(*http2clientConnReadLoop).run(0xc00011bfa8, 0x0, 0x0)
        /usr/lib/go/src/net/http/h2_bundle.go:8246 +0x8d
net/http.(*http2ClientConn).readLoop(0xc000682480)
        /usr/lib/go/src/net/http/h2_bundle.go:8174 +0x6f
created by net/http.(*http2Transport).newClientConn
        /usr/lib/go/src/net/http/h2_bundle.go:7174 +0x64a
```

```json
{
        "aururl": "https://aur.archlinux.org",
        "buildDir": "/home/user/.cache/yay",
        "absdir": "/home/user/.cache/yay/abs",
        "editor": "",
        "editorflags": "",
        "makepkgbin": "makepkg",
        "makepkgconf": "",
        "pacmanbin": "pacman",
        "pacmanconf": "/etc/pacman.conf",
        "redownload": "no",
        "rebuild": "no",
        "batchinstall": false,
        "answerclean": "",
        "answerdiff": "",
        "answeredit": "",
        "answerupgrade": "",
        "gitbin": "git",
        "gpgbin": "gpg",
        "gpgflags": "",
        "mflags": "",
        "sortby": "votes",
        "searchby": "name-desc",
        "gitflags": "",
        "removemake": "ask",
        "sudobin": "sudo",
        "sudoflags": "",
        "requestsplitn": 150,
        "sortmode": 0,
        "completionrefreshtime": 7,
        "sudoloop": false,
        "timeupdate": false,
        "devel": false,
        "cleanAfter": false,
        "provides": true,
        "pgpfetch": true,
        "upgrademenu": true,
        "cleanmenu": true,
        "diffmenu": true,
        "editmenu": false,
        "combinedupgrade": false,
        "useask": false
}
```

**Comment by Jguer** [comment]
Can't reproduce but will check
Do you have any of the following installed:
```
99 aur/boost1.69-libs 1.69.0-4 (+0 0.00%) (Orphaned) 
    Free peer-reviewed portable C++ source libraries - runtime libraries
98 aur/boost1.69 1.69.0-4 (+0 0.00%) (Orphaned) 
    Free peer-reviewed portable C++ source libraries - development headers
97 aur/intervalset 1.2.0-3 (+0 0.00%) 
    C++ library to manage sets of integral closed intervals — based on Boost.Icl
96 aur/eigenpy 2.1.2-1 (+0 0.00%) 
    Bindings between numpy and eigen using boost::python
95 aur/boost-di-git 1.0.1.r418.g388364952-1 (+0 0.00%) 
    Boost (experimental) c++14 dependency injection library (developmental version)
94 aur/python-minieigen-git 20200217.b2182a0-1 (+0 0.00%) 
    Boost::Python wrapper for parts of the Eigen c++ library
93 aur/lightgbm-cuda 2.2.3-1 (+0 0.00%) 
    Distributed gradient boosting framework based on decision tree algorithms.
92 aur/perl6-router-boost 0.0.1-2 (+0 0.00%) (Orphaned) 
    Routing engine for perl6
91 aur/python-catboost 0.22-1 (+0 0.00%) 
    Fast, scalable, high performance gradient boosting on decision trees
90 aur/luftikus 20140826-1 (+0 0.00%) 
    distrho port of EQ plugin (VST). digital adaptation of an analog EQ with fixed half-octave bands and additional high frequency boost
89 aur/azmq-git 0-1 (+0 0.00%) 
    C++ language binding library integrating ZeroMQ with Boost Asio
88 aur/boost.expected-git r341.2d1babd-1 (+0 0.00%) (Orphaned) 
    Utility class to represent expected monad
87 aur/websocketpp-git-dev 0.8.1.1702.bc0dc57-1 (+0 0.00%) 
    C++/Boost Asio based websocket client/server library, Develop branch
86 aur/dm-writeboost-tools 1.0.1-1 (+0 0.00%) (Orphaned) 
    Nice tools for dm-writeboost
85 aur/ros-melodic-random-numbers 0.3.2-4 (+0 0.00%) 
    ROS - This library contains wrappers for generating floating point values, integers, quaternions using boost libraries.
84 aur/mingw-w64-xgboost 0.7-1 (+0 0.00%) 
    An optimized distributed gradient boosting library designed to be highly efficient, flexible and portable (mingw-w64)
83 aur/r-bh 1.72.0_3-1 (+0 0.00%) 
    Boost C++ Header Files
82 aur/python-lightgbm-cuda 2.2.3-1 (+0 0.00%) 
    Distributed gradient boosting framework based on decision tree algorithms.
81 aur/boost-stacktrace-backtrace 1.71.0-1 (+0 0.00%) 
    Boost.stacktrace backtrace variant
80 aur/python-pylgbst 1.0.1-2 (+0 0.00%) 
    LEGO Boost python module
79 aur/boost-numeric-bindings-svn r86799-1 (+0 0.00%) 
    Boost Bindings is a bindings library (not just) for Boost.Ublas. It offers an easy way of calling BLAS, LAPACK, UMFPACK, MUMPS and many other mature legacy numerical codes from within C++.
78 aur/boost-di 1.1.0-1 (+0 0.00%) 
    Boost (experimental) c++14 dependency injection library
77 aur/mingw-w64-boost-python 1.62.0-1 (+0 0.00%) (Orphaned) (Out-of-date 2017-08-01) 
    Free peer-reviewed portable C++ source libraries (mingw-w64, python)
76 aur/swiften4-git 4.0.2.r6.gbb3bd8a32-1 (+0 0.00%) 
    XMPP library written in C++ with Boost (4.x branch)
75 aur/perl-type-tiny-xs 0.012-1 (+0 0.00%) 
    provides an XS boost for some of Type::Tiny's built-in type constraints
74 aur/boost-sml-git v1.0.1.r314.gdd2464f-1 (+0 0.00%) 
    Your scalable C++14 header State Machine Library with no dependencies
73 aur/ros-melodic-socketcan-interface 0.8.1-3 (+0 0.00%) 
    Generic CAN interface description with helpers for filtering and driver implementation. Further a socketcan implementation based on boost::asio is included.
72 aur/dm-writeboost 2.2.10-1 (+0 0.00%) (Orphaned) 
    Log-structured Caching for Linux
71 aur/android-x86-64-boost 1.71.0-1 (+0 0.00%) 
    Free peer-reviewed portable C++ source libraries (Android, x86-64)
70 aur/ros-indigo-ecl-sigslots 0.61.18-1 (+0 0.00%) 
    ROS - Provides a signal/slot mechanism (in the same vein as qt sigslots, boost::signals etc for intra-process communication.
69 aur/android-x86-boost 1.71.0-1 (+0 0.00%) 
    Free peer-reviewed portable C++ source libraries (Android, x86)
68 aur/boost.outcome-git r1019.4851926-1 (+0 0.00%) (Orphaned) 
    Utilities for modern error reporting and propagation in C++ applications
67 aur/gmabooster 09c-4 (+0 0.00%) 
    Tool to (over)clock Intel 945GM/GME/GMS/GSE, 943/940GML/GU, and GMA 950.
66 aur/rrn 0.0.1-3 (+0 0.00%) 
    recursive renaming tool written in C ++, uses boost library
65 aur/android-armv7a-eabi-boost 1.71.0-1 (+0 0.00%) 
    Free peer-reviewed portable C++ source libraries (Android, armv7a-eabi)
64 aur/json-spirit 4.18-1 (+0 0.00%) 
    JSON Spirit is a C++ JSON library using Boost Spirit for parsing.
63 aur/android-aarch64-boost 1.71.0-1 (+0 0.00%) 
    Free peer-reviewed portable C++ source libraries (Android, aarch64)
62 aur/ros-jade-random-numbers 0.3.0-1 (+1 0.00%) (Orphaned) 
    ROS - This library contains wrappers for generating floating point values, integers, quaternions using boost libraries.
61 aur/boost-nowide 1.64.0-1 (+1 0.00%) (Orphaned) 
    Boost.Nowide is a library implemented by Artyom Beilis that make cross platform Unicode aware programming easier.
60 aur/booster-gtk-themes 1.2-2 (+1 0.00%) 
    Booster Themes - Military Edition
59 aur/ros-lunar-rosboost-cfg 1.14.2-1 (+1 0.00%) 
    ROS - Contains scripts used by the rosboost-cfg tool for determining cflags/lflags/etc.
58 aur/vmdebootstrap 1.6-2 (+1 0.00%) 
    debootstrap installs a basic Debian system into a directory, for use with chroot(8). vmdeboostrap is a wrapper around it to install Debian into a disk image, which can be used with a virtual machine (such as KVM).
57 aur/boost-numeric-bindings-git 0.52.1f994e8-1 (+1 0.00%) 
    Boost Bindings is a bindings library (not just) for Boost.Ublas. It offers an easy way of calling BLAS, LAPACK, UMFPACK, MUMPS and many other mature legacy numerical codes from within C++.
56 aur/dtboost 1.6.15-2 (+1 0.00%) 
    A daemon that changes priority (CPU and disk I/O) and limits CPU usage of your applications on the fly
55 aur/ros-indigo-random-numbers 0.3.0-4 (+1 0.00%) (Orphaned) 
    ROS - This library contains wrappers for generating floating point values, integers, quaternions using boost libraries.
54 aur/ros-lunar-random-numbers 0.3.1-2 (+1 0.00%) 
    ROS - This library contains wrappers for generating floating point values, integers, quaternions using boost libraries.
53 aur/ros-kinetic-rosboost-cfg 1.13.4-1 (+1 0.00%) (Orphaned) 
    ROS - Contains scripts used by the rosboost-cfg tool for determining cflags/lflags/etc.
52 aur/pydio-booster 1:1.0.2-2 (+1 0.00%) (Orphaned) (Out-of-date 2017-05-16) 
    Pydio Booster is a unique tool developed to easily boost your Pydio installation performance
51 aur/ros-kinetic-random-numbers 0.3.1-1 (+1 0.00%) 
    ROS - This library contains wrappers for generating floating point values, integers, quaternions using boost libraries.
50 aur/pianobooster-git v0.7.2.r0.g9504171-1 (+1 0.92%) 
    A MIDI file player that teaches you how to play the piano
49 aur/python-catboost-gpu-git 0.13-1 (+1 0.00%) 
    CatBoost is an open-source gradient boosting on decision trees library with categorical features support out of the box.
48 aur/ros-jade-rosboost-cfg 1.12.7-1 (+1 0.00%) (Orphaned) 
    ROS - Contains scripts used by the rosboost-cfg tool for determining cflags/lflags/etc.
47 aur/pianobooster-qt5-git r1053.94c58b1-1 (+1 0.02%) 
    MIDI file player that teaches you how to play the piano (Qt5 port with fixes
46 aur/tbb-boost-git 20110215-1 (+1 0.00%) 
    Parallel implementation of boostexter's scored text classifier
45 aur/python-lightgbm 2.3.0-1 (+1 0.00%) 
    Distributed gradient boosting framework based on decision tree algorithms.
44 aur/icsiboost-svn 172-1 (+1 0.00%) 
    Adaboost with decision stumps, compatible with boostexter
43 aur/boost171 1.71.0-2 (+1 0.73%) 
    Free peer-reviewed portable C++ source libraries
42 aur/websocketpp-git 0.6.0.1461.c5510d6-1 (+1 0.00%) (Out-of-date 2017-12-03) 
    C++/Boost Asio based websocket client/server library
41 aur/eos_portable_archive 5.1-3 (+1 0.00%) 
    A portable binary archive to be used with boost::serialization
40 aur/ros-indigo-rosboost-cfg 1.11.12-1 (+1 0.00%) (Orphaned) 
    ROS - Contains scripts used by the rosboost-cfg tool for determining cflags/lflags/etc.
39 aur/lightgbm 2.3.0-1 (+1 0.00%) 
    Distributed gradient boosting framework based on decision tree algorithms.
38 aur/boost-63-compat 1.63.0-1 (+2 0.00%) 
    Free peer-reviewed portable C++ source libraries - compat version
37 aur/pianobooster 0.6.4b-1 (+2 0.81%) (Out-of-date 2020-02-23) 
    A MIDI file player that teaches you how to play the piano
36 aur/ros-melodic-rosboost-cfg 1.14.6-2 (+2 0.32%) 
    ROS - Contains scripts used by the rosboost-cfg tool for determining cflags/lflags/etc.
35 aur/boost-build-git r11135.7d80077-1 (+2 0.00%) (Orphaned) 
    Boost.Build makes it easy to build C++ projects, everywhere.
34 aur/mtxclient 0.2.1-1 (+2 0.00%) 
    Client API library for Matrix, built on top of Boost.Asio<Paste>
33 aur/icsiboost 160-1 (+2 0.00%) 
    Open-source implementation of Boostexter (Adaboost based classifier)
32 aur/ibus-typing-booster-git git-1 (+2 0.08%) 
    A completion input method for faster typing, git version.
31 aur/catboost-git 0.12.2-3 (+2 0.00%) 
    CatBoost is an open-source gradient boosting on decision trees library with categorical features support out of the box.
30 aur/turtle 1.3.1-1 (+3 0.00%) 
    A C++ Mock_object library based on Boost with a focus on usability, simplicity and flexibility.
29 aur/swiften-git 4.0beta2.r191.gf93289408-1 (+3 0.00%) 
    XMPP library written in C++ with Boost
28 aur/py++-svn 1856-2 (+3 0.00%) 
    Py++ package and Boost.Python library provide a complete solution for interfacing Python and C++
27 aur/boost-build-nightly 20140102-2 (+3 0.00%) (Orphaned) 
    Boost build system, Nightly build
26 aur/libodb-boost 2.5.0b17-1 (+3 0.00%) 
    The ODB boost profile library
25 aur/boost-65-compat 1.65.1-3 (+3 0.00%) 
    Free peer-reviewed portable C++ source libraries - compat version
24 aur/xfreq-git 2.1.65-1 (+4 0.00%) (Out-of-date 2016-11-07) 
    Processor Monitoring w/ Turbo Boost, Temps, C-States, Features, Tasks scheduling
23 aur/r-catools 1.17.1-1 (+4 0.00%) (Orphaned) (Out-of-date 2018-07-24) 
    Moving (rolling, running) window statistic functions, read/write for GIF and ENVI binary files, fast calculation of AUC, LogitBoost classifier, base64 encoder/decoder, round-off-error-free sum and cumsum, etc.
22 aur/deditor 0.4.0-1 (+4 0.00%) 
    The editor that boosts your python development
21 aur/cerebro-git v0.3.0.r10.g554391c-1 (+5 0.02%) (Orphaned) 
    Open-source productivity booster with a brain.
20 aur/nosqlbooster-mongodb 5.2.9-1 (+6 0.00%) 
    Shell-centric GUI tool for MongoDB
19 aur/ryzen-stabilizator-git r19.90a2f7a-1 (+8 0.00%) 
    Simple Go program to enable/disable C6 C-state, processor boosting, address space layout randomization (ASLR) and the Power Supply Idle Control workaround on an AMD Ryzen processor, in order to help with the infamous 'MCE-random-reboots-while-idle' issue.
18 aur/boost.process 0.5-1 (+8 0.00%) 
    Flexible framework for the C++ programming language to manage running programs
17 aur/lib32-boost-libs 1.65.1-1 (+9 0.30%) (Out-of-date 2018-08-10) 
    Free peer-reviewed portable C++ source libraries - Runtime (32 bit)
16 aur/python-xgboost-git r4049.911a90283-1 (+10 0.02%) 
    XGBoost Python 3 wrapper
15 aur/xgboost-git r4049.911a90283-1 (+10 0.02%) 
    An optimized distributed gradient boosting library designed to be highly efficient, flexible and portable
14 aur/perl-boost-geometry-utils 0.15-1 (+10 0.00%) 
    Boost::Geometry::Utils - Bindings for the Boost Geometry library
13 aur/boostnote-bin 0.15.0-1 (+11 0.20%) 
    Open source note-taking app for programmers. Official binary.
12 aur/py++ 1.0.0-3 (+16 0.38%) 
    Py++ package and Boost.Python library provide a complete solution for interfacing Python and C++
11 aur/fasd-git 1.0.1.r7.g90b531a-1 (+18 0.00%) 
    Command-line productivity booster, offers quick access to files and directories
10 aur/cerebro 0.3.2-1 (+18 0.00%) (Orphaned) 
    Open-source productivity booster with a brain.
9 aur/mingw-w64-boost 1.72.0-1 (+21 0.13%) 
    Free peer-reviewed portable C++ source libraries (mingw-w64)
8 aur/boost-build 4.0.0-1 (+32 0.00%) 
    Boost.Build makes it easy to build C++ projects, everywhere.
7 aur/boostnote 0.15.0-1 (+56 0.27%) 
    Open source note-taking app for programmers
6 community/websocketpp 0.8.1-1 (120.7 KiB 1012.0 KiB) 
    C++/Boost Asio based websocket client/server library
5 community/swiften 4.0.2-1 (2.5 MiB 13.8 MiB) 
    XMPP library written in C++ with Boost
4 community/fasd 1.0.1-2 (12.3 KiB 24.0 KiB) 
    Command-line productivity booster, offers quick access to files and directories
3 extra/ibus-typing-booster 2.7.3-1 (6.8 MiB 8.8 MiB) 
    Predictive input method for the IBus platform
2 extra/boost-libs 1.72.0-1 (2.6 MiB 10.5 MiB) 
    Free peer-reviewed portable C++ source libraries - runtime libraries
1 extra/boost 1.72.0-1 (13.2 MiB 175.7 MiB) 
    Free peer-reviewed portable C++ source libraries - development headers
==> Packages to install (eg: 1 2 3, 1-3 or ^4)
==> 
```

**Comment by rNoz** [comment]
Yes, i.e. boost and boost-libs (1.72.0-1)
