### ISSUE TITLE
panic if vim not in $PATH

### ISSUE THREAD

**Issue by sosiska** [Jguer/yay#1207]
#### Affected Version
yay v9.4.6 - libalpm v12.0.1
#### Issue
panic if `vim` not in $PATH

1. Remove vim from $PATH
2. yay -S oracle-instantclient-sqlplus --editmenu
3. Select edit PKGBUILD
#### Output
`yay -S oracle-instantclient-sqlplus --editmenu`                                                                                                                                
```
:: Checking for conflicts...
:: Checking for inner conflicts...
[Aur: 2]  oracle-instantclient-basic-19.5.0.0.0-1  oracle-instantclient-sqlplus-19.5.0.0.0-1

  2 oracle-instantclient-basic       (Build Files Exist)
  1 oracle-instantclient-sqlplus     (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> n
:: PKGBUILD up to date, Skipping (1/2): oracle-instantclient-sqlplus
:: PKGBUILD up to date, Skipping (2/2): oracle-instantclient-basic
  2 oracle-instantclient-basic       (Build Files Exist)
  1 oracle-instantclient-sqlplus     (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> n
:: Parsing SRCINFO (1/2): oracle-instantclient-basic
:: Parsing SRCINFO (2/2): oracle-instantclient-sqlplus
  2 oracle-instantclient-basic       (Build Files Exist)
  1 oracle-instantclient-sqlplus     (Build Files Exist)
==> PKGBUILDs to edit?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 1
exec: "vim": executable file not found in $PATH
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.editor(0xc0004762c0, 0xc00014e090, 0x1, 0x1, 0xc000436a50)
	config.go:247 +0x1172
main.editPkgbuilds(0xc0003f2da0, 0x1, 0x1, 0xc00039c3c0, 0xc00039c300, 0xc0003f2da0)
	install.go:784 +0x476
main.install(0xc000012380, 0x0, 0x0)
	install.go:292 +0x1e60
main.handleSync(0xa07d53, 0x1)
	cmd.go:280 +0x53a
main.handleCmd(0x0, 0x0)
	cmd.go:159 +0x10f
main.main()
	main.go:231 +0xeb
```

**Comment by parkerlreed** [comment]
I assume EDITOR is set to vim and it's not installed?

**Comment by sosiska** [comment]
> 
> 
> I assume EDITOR is set to vim and it's not installed?

Maybe, it was clear installation of Manjaro Architect, I will check it tomorow because it is on my workstation.

**Comment by sosiska** [comment]
Yes, it is.
