### ISSUE TITLE
yay crash

### ISSUE THREAD

**Issue by captn3m0** [Jguer/yay#1365]
#### Affected Version

`yay v10.0.4 - libalpm v12.0.2`

**Describe the bug**
Ran a normal upgrade with `yay`, and it crashed.

**To Reproduce**

I couldn't reproduce this, but it happened while running a normal upgrade.

**Expected behavior**
`yay` doesn't crash

**Output**

```
yay
[sudo] password for nemo:
:: Synchronizing package databases...
 core                                                  131.7 KiB  1197 KiB/s 00:00 [###############################################] 100%
 extra                                                1663.6 KiB  2.58 MiB/s 00:01 [###############################################] 100%
 community                                               5.2 MiB  2.78 MiB/s 00:02 [###############################################] 100%
 multilib is up to date
 sublime-text is up to date
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...

Packages (9) bluez-5.55-1  bluez-libs-5.55-1  bluez-utils-5.55-1  discord-0.0.12-1  htop-3.0.1-2  linux-5.8.8.arch1-1
             linux-headers-5.8.8.arch1-1  pkcs11-helper-1.26.0-2  rubberband-1.9-1

Total Download Size:   144.16 MiB
Total Installed Size:  370.32 MiB
Net Upgrade Size:        1.41 MiB

:: Proceed with installation? [Y/n]
:: Retrieving packages...
 linux-5.8.8.arch1-1-x86_64                             72.1 MiB  3.37 MiB/s 00:21 [###############################################] 100%
 linux-headers-5.8.8.arch1-1-x86_64                     22.4 MiB  3.35 MiB/s 00:07 [###############################################] 100%
 bluez-5.55-1-x86_64                                   818.8 KiB  3.24 MiB/s 00:00 [###############################################] 100%
 bluez-libs-5.55-1-x86_64                               96.2 KiB  6.71 MiB/s 00:00 [###############################################] 100%
 bluez-utils-5.55-1-x86_64                            1203.2 KiB  4.70 MiB/s 00:00 [###############################################] 100%
 htop-3.0.1-2-x86_64                                    91.0 KiB  3.70 MiB/s 00:00 [###############################################] 100%
 pkcs11-helper-1.26.0-2-x86_64                          69.7 KiB  3.40 MiB/s 00:00 [###############################################] 100%
 discord-0.0.12-1-x86_64                                47.2 MiB  4.94 MiB/s 00:10 [###############################################] 100%
 rubberband-1.9-1-x86_64                               204.2 KiB  2.85 MiB/s 00:00 [###############################################] 100%
(9/9) checking keys in keyring                                                     [###############################################] 100%
(9/9) checking package integrity                                                   [###############################################] 100%
(9/9) loading package files                                                        [###############################################] 100%
(9/9) checking for file conflicts                                                  [###############################################] 100%
(9/9) checking available disk space                                                [###############################################] 100%
:: Running pre-transaction hooks...
(1/2) Removing linux initcpios...
(2/2) Remove DKMS modules
==> dkms remove --no-depmod -m v4l2loopback -v 0.12.5 -k 5.8.7-arch1-1
==> depmod 5.8.7-arch1-1
:: Processing package changes...
(1/9) upgrading bluez                                                              [###############################################] 100%
(2/9) upgrading bluez-libs                                                         [###############################################] 100%
(3/9) upgrading bluez-utils                                                        [###############################################] 100%
(4/9) upgrading discord                                                            [###############################################] 100%
(5/9) upgrading htop                                                               [###############################################] 100%
(6/9) upgrading linux                                                              [###############################################] 100%
(7/9) upgrading linux-headers                                                      [###############################################] 100%
(8/9) upgrading pkcs11-helper                                                      [###############################################] 100%
(9/9) upgrading rubberband                                                         [###############################################] 100%
:: Running post-transaction hooks...
(1/8) Reloading system manager configuration...
(2/8) Arming ConditionNeedsUpdate...
(3/8) Updating module dependencies...
(4/8) Install DKMS modules
==> dkms install --no-depmod -m v4l2loopback -v 0.12.5 -k 5.8.8-arch1-1
==> depmod 5.8.8-arch1-1
(5/8) Updating linux initcpios...
==> Building image from preset: /etc/mkinitcpio.d/linux.preset: 'default'
  -> -k /boot/vmlinuz-linux -c /etc/mkinitcpio.conf -g /boot/initramfs-linux.img
==> Starting build: 5.8.8-arch1-1
  -> Running build hook: [base]
  -> Running build hook: [udev]
  -> Running build hook: [autodetect]
  -> Running build hook: [keyboard]
==> WARNING: Possibly missing firmware for module: xhci_pci
  -> Running build hook: [keymap]
  -> Running build hook: [consolefont]
==> WARNING: consolefont: no font found in configuration
  -> Running build hook: [modconf]
  -> Running build hook: [block]
  -> Running build hook: [encrypt]
  -> Running build hook: [filesystems]
  -> Running build hook: [fsck]
==> Generating module dependencies
==> Creating gzip-compressed initcpio image: /boot/initramfs-linux.img
==> Image generation successful
==> Building image from preset: /etc/mkinitcpio.d/linux.preset: 'fallback'
  -> -k /boot/vmlinuz-linux -c /etc/mkinitcpio.conf -g /boot/initramfs-linux-fallback.img -S autodetect
==> Starting build: 5.8.8-arch1-1
  -> Running build hook: [base]
  -> Running build hook: [udev]
  -> Running build hook: [keyboard]
==> WARNING: Possibly missing firmware for module: xhci_pci
  -> Running build hook: [keymap]
  -> Running build hook: [consolefont]
==> WARNING: consolefont: no font found in configuration
  -> Running build hook: [modconf]
  -> Running build hook: [block]
==> WARNING: Possibly missing firmware for module: aic94xx
==> WARNING: Possibly missing firmware for module: wd719x
^\SIGQUIT: quit
PC=0x562e85ac0f68 m=0 sigcode=128

goroutine 1 [syscall]:
syscall.Syscall6(0xf7, 0x1, 0xe5cb, 0xc0000cf530, 0x1000004, 0x0, 0x0, 0x0, 0xc0000cf578, 0x562e85ada6be)
	syscall/asm_linux_amd64.s:41 +0x5 fp=0xc0000cf4e0 sp=0xc0000cf4d8 pc=0x562e85ac0f45
os.(*Process).blockUntilWaitable(0xc0001287e0, 0x8, 0xc0000b2e40, 0xc0000cf618)
	os/wait_waitid.go:32 +0xa6 fp=0xc0000cf5d0 sp=0xc0000cf4e0 pc=0x562e85ae1446
os.(*Process).wait(0xc0001287e0, 0x562e85e62f90, 0x562e85e62f98, 0x562e85e62f88)
	os/exec_unix.go:22 +0x3b fp=0xc0000cf648 sp=0xc0000cf5d0 pc=0x562e85adb07b
os.(*Process).Wait(...)
	os/exec.go:125
os/exec.(*Cmd).Wait(0xc0000c4dc0, 0x0, 0x0)
	os/exec/exec.go:507 +0x65 fp=0xc0000cf6c0 sp=0xc0000cf648 pc=0x562e85cdb525
os/exec.(*Cmd).Run(0xc0000c4dc0, 0x8, 0x0)
	os/exec/exec.go:341 +0x5e fp=0xc0000cf6e8 sp=0xc0000cf6c0 pc=0x562e85cda97e
main.show(0xc0000c4dc0, 0xc0000c4dc0, 0x2)
	github.com/Jguer/yay/v10/exec.go:21 +0x8b fp=0xc0000cf730 sp=0xc0000cf6e8 pc=0x562e85d2662b
main.earlyPacmanCall(0xc0000cff48, 0xc0000b45f0, 0x2, 0x2)
	github.com/Jguer/yay/v10/install.go:448 +0x3a7 fp=0xc0000cf868 sp=0xc0000cf730 pc=0x562e85d2cae7
main.install(0xc0000cff48, 0xc0000b45f0, 0x0, 0x0, 0x0)
	github.com/Jguer/yay/v10/install.go:83 +0x3c25 fp=0xc0000cfdb0 sp=0xc0000cf868 pc=0x562e85d2c045
main.handleSync(0xc0000cff48, 0xc0000b45f0, 0x562e85d4e047, 0x1)
	github.com/Jguer/yay/v10/cmd.go:298 +0x5b8 fp=0xc0000cfe60 sp=0xc0000cfdb0 pc=0x562e85d1efb8
main.handleCmd(0xc0000cff48, 0xc0000b45f0, 0x10, 0xc0000b45f0)
	github.com/Jguer/yay/v10/cmd.go:164 +0x134 fp=0xc0000cfed8 sp=0xc0000cfe60 pc=0x562e85d1d434
main.main()
	github.com/Jguer/yay/v10/main.go:196 +0x296 fp=0xc0000cff88 sp=0xc0000cfed8 pc=0x562e85d375f6
runtime.main()
	runtime/proc.go:204 +0x209 fp=0xc0000cffe0 sp=0xc0000cff88 pc=0x562e85a3c589
runtime.goexit()
	runtime/asm_amd64.s:1374 +0x1 fp=0xc0000cffe8 sp=0xc0000cffe0 pc=0x562e85a6e781

rax    0xf7
rbx    0xc000028800
rcx    0x562e85ac0f6a
rdx    0xc0000cf530
rdi    0x1
rsi    0xe5cb
rbp    0xc0000cf5c0
rsp    0xc0000cf4d8
r8     0x0
r9     0x0
r10    0x1000004
r11    0x212
r12    0xffffffffffffffff
r13    0x2b
r14    0x2a
r15    0xaa
rip    0x562e85ac0f68
rflags 0x212
cs     0x33
fs     0x0
gs     0x0
```

**Comment by grandchild** [comment]
> ```^\SIGQUIT: quit```

If I'm not mistaken and Go prints this out itself, this line suggests that something sent a SIGQUIT (-3) signal to the yay process.

I can reproduce this if I press the associated keyboard shortcut (which I also only just learned about through this :smile:) `Ctrl`+`\`:

* Run `yay`
* (Enter sudo pw if prompted)
* Press `Ctrl` + `\` during repo sync
* Watch coredump ;)

@captn3m0, could it be you hit those keys when that happened?

**Comment by grandchild** [comment]
https://www.gnu.org/software/libc/manual/html_node/Termination-Signals.html -- where I learned about it.

**Comment by captn3m0** [comment]
I don't think I pressed the keyboard shortcut. Wondering if something else triggered the signal. Just wanted to post this in case it wasn't a fluke.

**Comment by grandchild** [comment]
Since it's not reproducible, this should be closed until it can be reproduced.
