### ISSUE TITLE
segmentation violation when using yay -Ss

### ISSUE THREAD

**Issue by VRichardJP** [Jguer/yay#1447]
### Affected Version
`yay v10.1.2 - libalpm v12.0.1`
According to pacman the actual package version is yay-10.1.2-1

### Describe the bug
`yay -Ss <anything>` cause segmentation violation error
the equivalent command with pacman works fine.

### Reproduction Steps

`$ yay -Ss libzip`

### Expected behavior
no segfault

### Output

Example with pacman:
```bash
$ pacman -Ss libzip
extra/libzip 1.7.3-1 [installed]
    A C library for reading, creating, and modifying zip archives
```

Same but with yay:
```bash
$ yay -Ss libzip
unexpected fault address 0xffffffff
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0xffffffff pc=0x5630aaa73e99]

goroutine 1 [running]:
runtime.throw(0x5630aac413fd, 0x5)
	runtime/panic.go:1116 +0x74 fp=0xc00025ba08 sp=0xc00025b9d8 pc=0x5630aa924eb4
runtime.sigpanic()
	runtime/signal_unix.go:749 +0x405 fp=0xc00025ba38 sp=0xc00025ba08 pc=0x5630aa93a9a5
github.com/Jguer/go-alpm/v2.(*list).forEach(0xffffffff, 0xc00025ba80, 0x5630aaa70e8f, 0xc00005a800)
	github.com/Jguer/go-alpm/v2@v2.0.2/types.go:113 +0x39 fp=0xc00025ba60 sp=0xc00025ba38 pc=0x5630aaa73e99
github.com/Jguer/go-alpm/v2.PackageList.ForEach(0xffffffff, 0x7f4a58000b80, 0xc00038ae20, 0xffffff01, 0xc00038ae20)
	github.com/Jguer/go-alpm/v2@v2.0.2/package.go:48 +0x69 fp=0xc00025bab0 sp=0xc00025ba60 pc=0x5630aaa72049
github.com/Jguer/go-alpm/v2.(*PackageList).ForEach(0xc00038ae10, 0xc00038ae20, 0x1, 0x1)
	<autogenerated>:1 +0x51 fp=0xc00025bae8 sp=0xc00025bab0 pc=0x5630aaa795b1
github.com/Jguer/yay/v10/pkg/db/ialpm.(*AlpmExecutor).SyncPackages.func1(0x5630aad69840, 0xc0004e2ba0, 0xc00025bbf0, 0x5630aa8fcab0)
	github.com/Jguer/yay/v10/pkg/db/ialpm/alpm.go:328 +0x164 fp=0xc00025bb40 sp=0xc00025bae8 pc=0x5630aac145c4
github.com/Jguer/go-alpm/v2.DBList.ForEach.func1(0x7f4a580220f0, 0x0, 0x7f4a74837a78)
	github.com/Jguer/go-alpm/v2@v2.0.2/db.go:36 +0x75 fp=0xc00025bb80 sp=0xc00025bb40 pc=0x5630aaa745d5
github.com/Jguer/go-alpm/v2.(*list).forEach(0x7f4a5801ff00, 0xc00025bbc8, 0xc000284290, 0xc00005a800)
	github.com/Jguer/go-alpm/v2@v2.0.2/types.go:113 +0x4a fp=0xc00025bba8 sp=0xc00025bb80 pc=0x5630aaa73eaa
github.com/Jguer/go-alpm/v2.DBList.ForEach(0x7f4a5801ff00, 0x7f4a58000b80, 0xc0006263f0, 0x5630aaf7df01, 0xc0006263f0)
	github.com/Jguer/go-alpm/v2@v2.0.2/db.go:35 +0x69 fp=0xc00025bbf8 sp=0xc00025bba8 pc=0x5630aaa70209
github.com/Jguer/go-alpm/v2.(*DBList).ForEach(0xc000284280, 0xc0006263f0, 0x1, 0xc0000b7c70)
	<autogenerated>:1 +0x51 fp=0xc00025bc30 sp=0xc00025bbf8 pc=0x5630aaa78c51
github.com/Jguer/yay/v10/pkg/db/ialpm.(*AlpmExecutor).SyncPackages(0xc000298000, 0xc000284290, 0x1, 0x1, 0x5630aaf7dfe0, 0x7f4a58000b80, 0xc0000b7cc0)
	github.com/Jguer/yay/v10/pkg/db/ialpm/alpm.go:321 +0xb0 fp=0xc00025bc68 sp=0xc00025bc30 pc=0x5630aac123b0
main.queryRepo(0xc000284290, 0x1, 0x1, 0x5630aad6aa40, 0xc000298000, 0x7, 0x9, 0x0)
	github.com/Jguer/yay/v10/query.go:244 +0x5b fp=0xc00025bcc8 sp=0xc00025bc68 pc=0x5630aac3651b
main.syncSearch(0xc000284290, 0x1, 0x1, 0x5630aad6aa40, 0xc000298000, 0x10, 0x0)
	github.com/Jguer/yay/v10/query.go:160 +0x165 fp=0xc00025bd80 sp=0xc00025bcc8 pc=0x5630aac359a5
main.handleSync(0xc0000b7f28, 0x5630aad6aa40, 0xc000298000, 0x1, 0xffffffffffffffff)
	github.com/Jguer/yay/v10/cmd.go:259 +0x174 fp=0xc00025be38 sp=0xc00025bd80 pc=0x5630aac187d4
main.handleCmd(0xc0000b7f28, 0x5630aad6aa40, 0xc000298000, 0x0, 0x300)
	github.com/Jguer/yay/v10/cmd.go:165 +0x14e fp=0xc00025beb0 sp=0xc00025be38 pc=0x5630aac1704e
main.main()
	github.com/Jguer/yay/v10/main.go:129 +0x46a fp=0xc00025bf88 sp=0xc00025beb0 pc=0x5630aac2f16a
runtime.main()
	runtime/proc.go:204 +0x209 fp=0xc00025bfe0 sp=0xc00025bf88 pc=0x5630aa9276c9
runtime.goexit()
	runtime/asm_amd64.s:1374 +0x1 fp=0xc00025bfe8 sp=0xc00025bfe0 pc=0x5630aa959a61

goroutine 51 [IO wait]:
internal/poll.runtime_pollWait(0x7f4a75b34e88, 0x72, 0x5630aad60da0)
	runtime/netpoll.go:222 +0x65
internal/poll.(*pollDesc).wait(0xc000292318, 0x72, 0x5630aad60d00, 0x5630aaf134c0, 0x0)
	internal/poll/fd_poll_runtime.go:87 +0x47
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000292300, 0xc000246000, 0x116e, 0x116e, 0x0, 0x0, 0x0)
	internal/poll/fd_unix.go:159 +0x1a5
net.(*netFD).Read(0xc000292300, 0xc000246000, 0x116e, 0x116e, 0x203000, 0x16000000fa, 0x1800000017)
	net/fd_posix.go:55 +0x51
net.(*conn).Read(0xc000214000, 0xc000246000, 0x116e, 0x116e, 0x0, 0x0, 0x0)
	net/net.go:182 +0x90
crypto/tls.(*atLeastReader).Read(0xc00028c060, 0xc000246000, 0x116e, 0x116e, 0x1ffb000000fd, 0x1ffc0007fff0, 0xc0000b9730)
	crypto/tls/conn.go:779 +0x62
bytes.(*Buffer).ReadFrom(0xc000218280, 0x5630aad5fc00, 0xc00028c060, 0x5630aa8fa767, 0x5630aacfdee0, 0x5630aad44100)
	bytes/buffer.go:204 +0xbb
crypto/tls.(*Conn).readFromUntil(0xc000218000, 0x5630aad5ff20, 0xc000214000, 0x5, 0xc000214000, 0x0)
	crypto/tls/conn.go:801 +0xf3
crypto/tls.(*Conn).readRecordOrCCS(0xc000218000, 0x0, 0x0, 0xc0000b9d38)
	crypto/tls/conn.go:608 +0x125
crypto/tls.(*Conn).readRecord(...)
	crypto/tls/conn.go:576
crypto/tls.(*Conn).Read(0xc000218000, 0xc00007e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	crypto/tls/conn.go:1252 +0x15f
bufio.(*Reader).Read(0xc000211200, 0xc0005dcb98, 0x9, 0x9, 0xc0000b9d38, 0x5630aad57300, 0x5630aab9cf4d)
	bufio/bufio.go:227 +0x224
io.ReadAtLeast(0x5630aad5fae0, 0xc000211200, 0xc0005dcb98, 0x9, 0x9, 0x9, 0xc00006c060, 0x0, 0x5630aad5fda0)
	io/io.go:314 +0x89
io.ReadFull(...)
	io/io.go:333
net/http.http2readFrameHeader(0xc0005dcb98, 0x9, 0x9, 0x5630aad5fae0, 0xc000211200, 0x0, 0x563000000000, 0xc0006261b0, 0x0)
	net/http/h2_bundle.go:1477 +0x89
net/http.(*http2Framer).ReadFrame(0xc0005dcb60, 0xc0006261b0, 0x0, 0x0, 0x0)
	net/http/h2_bundle.go:1735 +0xa5
net/http.(*http2clientConnReadLoop).run(0xc0000b9fa8, 0x0, 0x0)
	net/http/h2_bundle.go:8251 +0x8f
net/http.(*http2ClientConn).readLoop(0xc000102900)
	net/http/h2_bundle.go:8179 +0x71
created by net/http.(*http2Transport).newClientConn
	net/http/h2_bundle.go:7175 +0x685
```

**Comment by Morganamilo** [comment]
This happens when yay is build against a different version of pacman. Did you build yay then change to the pacman beta or -git? if so just rebuild yay.

**Comment by VRichardJP** [comment]
Indeed, I recently changed to pacman-git

Thanks!
