### ISSUE TITLE
yay -Ss crashes with SIGSEGV

### ISSUE THREAD

**Issue by RubenKelevra** [Jguer/yay#1456]
### Affected Version
yay v10.1.2 - libalpm v12.0.1

### Describe the bug
That's probably network related. So some service etc is down or something like that.

### Reproduction Steps
1. run `yay -Ss test`
2. get a segfault

### Expected behavior
Don't get a segfault, but a search result

### Output
```sh
[ruben@i3 ~]$ yay -S test
 -> Could not find all required packages:
	test (Target)
[ruben@i3 ~]$ yay -Ss test
unexpected fault address 0xffffffff
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0xffffffff pc=0x56397aaeae99]

goroutine 1 [running]:
runtime.throw(0x56397acb83fd, 0x5)
	runtime/panic.go:1116 +0x74 fp=0xc000159a08 sp=0xc0001599d8 pc=0x56397a99beb4
runtime.sigpanic()
	runtime/signal_unix.go:749 +0x405 fp=0xc000159a38 sp=0xc000159a08 pc=0x56397a9b19a5
github.com/Jguer/go-alpm/v2.(*list).forEach(0xffffffff, 0xc000159a80, 0x56397aae7e8f, 0xc000014c00)
	github.com/Jguer/go-alpm/v2@v2.0.2/types.go:113 +0x39 fp=0xc000159a60 sp=0xc000159a38 pc=0x56397aaeae99
github.com/Jguer/go-alpm/v2.PackageList.ForEach(0xffffffff, 0x56397c1f2910, 0xc0003f07e0, 0xffffff01, 0xc0003f07e0)
	github.com/Jguer/go-alpm/v2@v2.0.2/package.go:48 +0x69 fp=0xc000159ab0 sp=0xc000159a60 pc=0x56397aae9049
github.com/Jguer/go-alpm/v2.(*PackageList).ForEach(0xc0003f07d0, 0xc0003f07e0, 0x1, 0x1)
	<autogenerated>:1 +0x51 fp=0xc000159ae8 sp=0xc000159ab0 pc=0x56397aaf05b1
github.com/Jguer/yay/v10/pkg/db/ialpm.(*AlpmExecutor).SyncPackages.func1(0x56397ade0840, 0xc000371c10, 0xc000159bf0, 0x56397a973ab0)
	github.com/Jguer/yay/v10/pkg/db/ialpm/alpm.go:328 +0x164 fp=0xc000159b40 sp=0xc000159ae8 pc=0x56397ac8b5e4
github.com/Jguer/go-alpm/v2.DBList.ForEach.func1(0x56397c213c70, 0x1000000000000, 0x7f642c324e88)
	github.com/Jguer/go-alpm/v2@v2.0.2/db.go:36 +0x75 fp=0xc000159b80 sp=0xc000159b40 pc=0x56397aaeb5d5
github.com/Jguer/go-alpm/v2.(*list).forEach(0x56397c211a80, 0xc000159bc8, 0xc000176dc0, 0xc000014c00)
	github.com/Jguer/go-alpm/v2@v2.0.2/types.go:113 +0x4a fp=0xc000159ba8 sp=0xc000159b80 pc=0x56397aaeaeaa
github.com/Jguer/go-alpm/v2.DBList.ForEach(0x56397c211a80, 0x56397c1f2910, 0xc00048c030, 0x56397aff4f01, 0xc00048c030)
	github.com/Jguer/go-alpm/v2@v2.0.2/db.go:35 +0x69 fp=0xc000159bf8 sp=0xc000159ba8 pc=0x56397aae7209
github.com/Jguer/go-alpm/v2.(*DBList).ForEach(0xc000176db0, 0xc00048c030, 0x1, 0xc0000cdc70)
	<autogenerated>:1 +0x51 fp=0xc000159c30 sp=0xc000159bf8 pc=0x56397aaefc51
github.com/Jguer/yay/v10/pkg/db/ialpm.(*AlpmExecutor).SyncPackages(0xc0000e44b0, 0xc000176dc0, 0x1, 0x1, 0x56397aff4fe0, 0x56397c1f2910, 0xc0000cdcc0)
	github.com/Jguer/yay/v10/pkg/db/ialpm/alpm.go:321 +0xb0 fp=0xc000159c68 sp=0xc000159c30 pc=0x56397ac893d0
main.queryRepo(0xc000176dc0, 0x1, 0x1, 0x56397ade1a40, 0xc0000e44b0, 0x4dc, 0x63f, 0x0)
	github.com/Jguer/yay/v10/query.go:244 +0x5b fp=0xc000159cc8 sp=0xc000159c68 pc=0x56397acad53b
main.syncSearch(0xc000176dc0, 0x1, 0x1, 0x56397ade1a40, 0xc0000e44b0, 0x10, 0x0)
	github.com/Jguer/yay/v10/query.go:160 +0x165 fp=0xc000159d80 sp=0xc000159cc8 pc=0x56397acac9c5
main.handleSync(0xc0000cdf28, 0x56397ade1a40, 0xc0000e44b0, 0x1, 0xffffffffffffffff)
	github.com/Jguer/yay/v10/cmd.go:259 +0x174 fp=0xc000159e38 sp=0xc000159d80 pc=0x56397ac8f7f4
main.handleCmd(0xc0000cdf28, 0x56397ade1a40, 0xc0000e44b0, 0x0, 0x301)
	github.com/Jguer/yay/v10/cmd.go:165 +0x14e fp=0xc000159eb0 sp=0xc000159e38 pc=0x56397ac8e06e
main.main()
	github.com/Jguer/yay/v10/main.go:129 +0x46a fp=0xc000159f88 sp=0xc000159eb0 pc=0x56397aca618a
runtime.main()
	runtime/proc.go:204 +0x209 fp=0xc000159fe0 sp=0xc000159f88 pc=0x56397a99e6c9
runtime.goexit()
	runtime/asm_amd64.s:1374 +0x1 fp=0xc000159fe8 sp=0xc000159fe0 pc=0x56397a9d0a61

goroutine 35 [IO wait]:
internal/poll.runtime_pollWait(0x7f642d688e88, 0x72, 0x56397add7da0)
	runtime/netpoll.go:222 +0x65
internal/poll.(*pollDesc).wait(0xc0000e2698, 0x72, 0x56397add7d00, 0x56397af8a4c0, 0x0)
	internal/poll/fd_poll_runtime.go:87 +0x47
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0000e2680, 0xc00026a000, 0xf415, 0xf415, 0x0, 0x0, 0x0)
	internal/poll/fd_unix.go:159 +0x1a5
net.(*netFD).Read(0xc0000e2680, 0xc00026a000, 0xf415, 0xf415, 0x203000, 0xc, 0xc000272031)
	net/fd_posix.go:55 +0x51
net.(*conn).Read(0xc000010010, 0xc00026a000, 0xf415, 0xf415, 0x0, 0x0, 0x0)
	net/net.go:182 +0x90
crypto/tls.(*atLeastReader).Read(0xc000496320, 0xc00026a000, 0xf415, 0xf415, 0x73e4, 0xc00027202c, 0xc0000cf730)
	crypto/tls/conn.go:779 +0x62
bytes.(*Buffer).ReadFrom(0xc00006e280, 0x56397add6c00, 0xc000496320, 0x56397a971767, 0x56397ad74ee0, 0x56397adbb100)
	bytes/buffer.go:204 +0xbb
crypto/tls.(*Conn).readFromUntil(0xc00006e000, 0x56397add6f20, 0xc000010010, 0x5, 0xc000010010, 0xc000272031)
	crypto/tls/conn.go:801 +0xf3
crypto/tls.(*Conn).readRecordOrCCS(0xc00006e000, 0x0, 0x0, 0xc0000cfd38)
	crypto/tls/conn.go:608 +0x125
crypto/tls.(*Conn).readRecord(...)
	crypto/tls/conn.go:576
crypto/tls.(*Conn).Read(0xc00006e000, 0xc000386000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	crypto/tls/conn.go:1252 +0x15f
bufio.(*Reader).Read(0xc0001db0e0, 0xc0001d89d8, 0x9, 0x9, 0xc0000cfd38, 0x56397adce300, 0x56397ac13f6d)
	bufio/bufio.go:227 +0x224
io.ReadAtLeast(0x56397add6ae0, 0xc0001db0e0, 0xc0001d89d8, 0x9, 0x9, 0x9, 0xc000098050, 0x0, 0x56397add6da0)
	io/io.go:314 +0x89
io.ReadFull(...)
	io/io.go:333
net/http.http2readFrameHeader(0xc0001d89d8, 0x9, 0x9, 0x56397add6ae0, 0xc0001db0e0, 0x0, 0x563900000000, 0xc0001c8240, 0x0)
	net/http/h2_bundle.go:1477 +0x89
net/http.(*http2Framer).ReadFrame(0xc0001d89a0, 0xc0001c8240, 0x0, 0x0, 0x0)
	net/http/h2_bundle.go:1735 +0xa5
net/http.(*http2clientConnReadLoop).run(0xc0000cffa8, 0x0, 0x0)
	net/http/h2_bundle.go:8251 +0x8f
net/http.(*http2ClientConn).readLoop(0xc000001b00)
	net/http/h2_bundle.go:8179 +0x71
created by net/http.(*http2Transport).newClientConn
	net/http/h2_bundle.go:7175 +0x685

```

**Comment by Morganamilo** [comment]
You're yay and pacman version don't match. If you switched to/from pacman-git that's the issue. You just need to rebuild yay against the currently installed pacman.
