### ISSUE TITLE
Can't update python2-lxml

### ISSUE THREAD

**Issue by jazz-it** [Jguer/yay#1554]
### Affected Version
yay v10.3.0 - libalpm v13.0.0

### Describe the bug
Whilst trying to update the `python2-lxml` to the recent `v4.6.3-2`, yay throws an error and fails to complete the operation. It seems like versioning discrepancy. Output is here: https://hastebin.com/rinuwiyere.sql

### Expected behavior
I successfully updated the package with `sudo pamac upgrade`, therefore `yay` should handle it as well.

### Output
`$ yay -Syu`
```sh
:: Starting full system upgrade...
 there is nothing to do
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: Starting full system upgrade...
 there is nothing to do
:: Searching databases for updates...
:: Searching AUR for updates...
 -> libdbusmenu-qt4: local (0.9.3+16.04.20160218-2) is newer than AUR (0.9.3+16.04.20160218-1)
 -> php-box: local (3.8.0-3) is newer than AUR (2.7.5-1)
 -> Missing AUR Packages:  auracle  linux510-virtualbox-guest-modules  linux54-virtualbox-guest-modules
 -> Orphaned AUR Packages:  google-keep-nativefier  libdbusmenu-qt4  sni-qt
 -> Flagged Out Of Date AUR Packages:  insomnia  joplin-desktop  lando  superproductivity
:: 2 Packages to upgrade.
2  aur/joplin-desktop  1.7.11-2 -> 2.1.7-1
1  aur/python2-lxml    4.6.2-1  -> 4.6.3-2
==> Packages to exclude: (eg: "1 2 3", "1-3", "^4" or repo name)
==> 2
:: Checking for conflicts...
:: Checking for inner conflicts...
[Repo Make:1]  cython2-0.29.23-1
[Aur:1]  python2-lxml-4.6.3-2

==> Remove make dependencies after install? [y/N] 
  1 python2-lxml                             (Installed) (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> a
:: Deleting (1/1): /home/joe/.cache/yay/python2-lxml
:: Downloaded PKGBUILD (1/1): python2-lxml
  1 python2-lxml                             (Installed) (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> n
:: (1/1) Parsing SRCINFO: python2-lxml
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
resolving dependencies...
looking for conflicting packages...

Packages (1) cython2-0.29.23-1

Total Installed Size:  8.71 MiB

:: Proceed with installation? [Y/n] 
(1/1) checking keys in keyring                                                                   [#########################################################] 100%
(1/1) checking package integrity                                                                 [#########################################################] 100%
(1/1) loading package files                                                                      [#########################################################] 100%
(1/1) checking for file conflicts                                                                [#########################################################] 100%
(1/1) checking available disk space                                                              [#########################################################] 100%
:: Processing package changes...
(1/1) installing cython2                                                                         [#########################################################] 100%
:: Running post-transaction hooks...
(1/2) Arming ConditionNeedsUpdate...
(2/2) Checking for orphaned packages via hook...
lib32-lcms2 2.12-1
lib32-libgudev 236-1
lib32-libinstpatch 1.1.6-1
lib32-librsvg 2:2.50.7-1
lib32-nettle 3.7.2-1
lib32-portaudio 1:19.7.0-1
==> Making package: python2-lxml 4.6.3-2 (Wed Jul 14 09:15:27 2021)
==> Retrieving sources...
  -> Downloading lxml-4.6.3.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   121  100   121    0     0    477      0 --:--:-- --:--:-- --:--:--   476
100  926k    0  926k    0     0   992k      0 --:--:-- --:--:-- --:--:--  992k
==> Validating source files with sha512sums...
    lxml-4.6.3.tar.gz ... Passed
 -> cython2 not satisfied, flushing install queue
==> Making package: python2-lxml 4.6.3-2 (Wed Jul 14 09:15:28 2021)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found lxml-4.6.3.tar.gz
==> Validating source files with sha512sums...
    lxml-4.6.3.tar.gz ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting lxml-4.6.3.tar.gz with bsdtar
==> Sources are ready.
==> Making package: python2-lxml 4.6.3-2 (Wed Jul 14 09:15:29 2021)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting build()...
Traceback (most recent call last):
  File "setup.py", line 15, in <module>
    from setuptools import setup
  File "/usr/lib/python3.9/site-packages/setuptools/__init__.py", line 16, in <module>
    import setuptools.version
  File "/usr/lib/python3.9/site-packages/setuptools/version.py", line 1, in <module>
    import pkg_resources
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1367
    raise SyntaxError(e) from e
                            ^
SyntaxError: invalid syntax
==> ERROR: A failure occurred in build().
    Aborting...
error making: python2-lxml
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: Starting full system upgrade...
 there is nothing to do

 searching orphans ...
checking dependencies...

Packages (1) cython2-0.29.23-1

Total Removed Size:  8.71 MiB

:: Do you want to remove these packages? [Y/n]
```

**Comment by Morganamilo** [comment]
Looks like the package is trying to build against python 3 for some reason. don't see how yay could cause that.

**Comment by jazz-it** [comment]
For the reference: I switched to `pamac` and it smoothly updated this package with no issues.
