### ISSUE TITLE
invalid memory address or nil pointer dereference - cleaning up

### ISSUE THREAD

**Issue by 1Jo1** [Jguer/yay#1837]
### Affected Version

`yay v11.3.1.r60.g7612bb5 - libalpm v13.0.2`
`kernel-version: 5.15.79-1-lts`

### Describe the bug

I'm getting an invalid memory address runtime error when I'm install packages like `brave-bin` `gnome-ssh-askpass3`

### Reproduction Steps

1. `yay -Scc` //Clear cache
2. `yay -S brave-bin`

after clean up section the invalid memory address runtime error will be triggered
`yay -S brave-bin`
```
:: Checking for conflicts...
:: Checking for inner conflicts...
[Aur:1]  brave-bin-1:1.45.131-1

:: (1/1) Downloaded PKGBUILD: brave-bin
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> I
==> Making package: brave-bin 1:1.45.131-1 (Wed 23 Nov 2022 01:14:02 PM CET)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading brave-bin-1.45.131.zip...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  144M  100  144M    0     0  16.1M      0  0:00:08  0:00:08 --:--:-- 18.1M
  -> Found brave-bin.sh
  -> Found brave-browser.desktop
==> Validating source files with sha256sums...
    brave-bin-1.45.131.zip ... Passed
    brave-bin.sh ... Passed
    brave-browser.desktop ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
==> Starting prepare()...
==> Sources are ready.
==> Making package: brave-bin 1:1.45.131-1 (Wed 23 Nov 2022 01:14:14 PM CET)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Entering fakeroot environment...
==> Starting package()...
~/.cache/yay/brave-bin/pkg/brave-bin/usr ~/.cache/yay/brave-bin/src
==> Tidying install...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Removing static library files...
  -> Compressing man and info pages...
==> Checking for packaging issues...
==> Creating package "brave-bin"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: brave-bin 1:1.45.131-1 (Wed 23 Nov 2022 01:14:19 PM CET)
==> Cleaning up...
 -> runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	runtime/debug/stack.go:16 +0x19
main.main.func2()
	github.com/Jguer/yay/v11/main.go:138 +0x53
panic({0x564e81b75ee0, 0x564e81de2dd0})
	runtime/panic.go:884 +0x212
main.buildInstallPkgbuilds({0x564e81bdbf70?, 0xc0000300e8}, 0xc0001a7d70, {0x564e81bdfc18, 0xc0001ce1b0}, 0xc0000ee180, 0xc000363480, 0x0?, 0x1, 0xc00044c2d0, ...)
	github.com/Jguer/yay/v11/install.go:787 +0x1fed
main.install({0x564e81bdbf70?, 0xc0000300e8}, 0xc0001a7d70, {0x564e81bdfc18?, 0xc0001ce1b0}, 0x11?)
	github.com/Jguer/yay/v11/install.go:349 +0x26f4
main.handleSync({0x564e81bdbf70, 0xc0000300e8}, 0xc0001a7d70, {0x564e81bdfc18, 0xc0001ce1b0})
	github.com/Jguer/yay/v11/cmd.go:373 +0x79d
main.handleCmd({0x564e81bdbf70, 0xc0000300e8}, 0xc0001a7d70, {0x564e81bdfc18?, 0xc0001ce1b0?})
	github.com/Jguer/yay/v11/cmd.go:177 +0x3fd
main.main()
	github.com/Jguer/yay/v11/main.go:144 +0x87a
```

### Output
yay -Pg
```
{
	"aururl": "https://aur.archlinux.org",
	"aurrpcurl": "",
	"buildDir": "/home/jo/.cache/yay",
	"editor": "",
	"editorflags": "",
	"makepkgbin": "makepkg",
	"makepkgconf": "",
	"pacmanbin": "pacman",
	"pacmanconf": "/etc/pacman.conf",
	"redownload": "no",
	"rebuild": "no",
	"answerclean": "",
	"answerdiff": "",
	"answeredit": "",
	"answerupgrade": "",
	"gitbin": "git",
	"gpgbin": "gpg",
	"gpgflags": "",
	"mflags": "",
	"sortby": "votes",
	"searchby": "name-desc",
	"gitflags": "",
	"removemake": "ask",
	"sudobin": "sudo",
	"sudoflags": "",
	"version": "11.3.1.r60.g7612bb5",
	"requestsplitn": 150,
	"completionrefreshtime": 7,
	"maxconcurrentdownloads": 0,
	"bottomup": true,
	"sudoloop": false,
	"timeupdate": false,
	"devel": false,
	"cleanAfter": false,
	"provides": false,
	"pgpfetch": true,
	"upgrademenu": true,
	"cleanmenu": true,
	"diffmenu": true,
	"editmenu": false,
	"combinedupgrade": false,
	"useask": false,
	"batchinstall": false,
	"singlelineresults": false,
	"separatesources": true,
	"newinstallengine": false,
	"debug": false
}

```

**Comment by 1Jo1** [comment]
I fixed that bug, I just removed yay completely and reinstall it, it works now
