### ISSUE TITLE
Failed to build yay

### ISSUE THREAD

**Issue by OptixWolf** [Jguer/yay#1886]
### Affected Version

yay-git 11.3.1.r0.g3f5dffc-1

### Describe the bug

Can't build the package because of an error

### Reproduction Steps

1. sudo pacman -S --needed git base-devel
2. git clone https://aur.archlinux.org/yay.git
3. cd yay
4. makepkg -si

### Expected behavior

It should install yay

### Output

```sh
Klone nach 'yay'...
remote: Enumerating objects: 444, done.
remote: Counting objects: 100% (444/444), done.
remote: Compressing objects: 100% (329/329), done.
remote: Total 444 (delta 112), reused 443 (delta 112), pack-reused 0
Empfange Objekte: 100% (444/444), 93.58 KiB | 1.49 MiB/s, fertig.
Löse Unterschiede auf: 100% (112/112), fertig.
==> Erstelle Paket: yay 11.3.1-1 (Do 05 Jan 2023 15:57:43 CET)
==> Prüfe Laufzeit-Abhängigkeiten...
==> Prüfe Buildtime-Abhängigkeiten...
==> Empfange Quellen...
  -> Lade yay-11.3.1.tar.gz herunter...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  390k  100  390k    0     0   581k      0 --:--:-- --:--:-- --:--:--  581k
==> Überprüfe source Dateien mit sha256sums...
    yay-11.3.1.tar.gz ... Erfolg
==> Entpacke Quellen...
  -> Entpacke yay-11.3.1.tar.gz mit bsdtar
==> Beginne build()...
go build -trimpath -mod=readonly -modcacherw pacman-git -ldflags '-X "main.yayVersion=11.3.1" -X "main.localePath=/usr/share/locale/" -linkmode=external' -buildmode=pie -o yay
panic: path "-X \"main.yayVersion=11.3.1\" -X \"main.localePath=/usr/share/locale/\" -linkmode=external" not in error "invalid import path \"-X \\\"main.yayVersion=11.3.1\\\" -X \\\"main.localePath=/usr/share/locale/\\\" -linkmode=external\"" [recovered]
        panic: path "-X \"main.yayVersion=11.3.1\" -X \"main.localePath=/usr/share/locale/\" -linkmode=external" not in error "invalid import path \"-X \\\"main.yayVersion=11.3.1\\\" -X \\\"main.localePath=/usr/share/locale/\\\" -linkmode=external\""

goroutine 1 [running]:
cmd/go/internal/load.(*preload).flush(0xc000383b50)
        /usr/lib/go/src/cmd/go/internal/load/pkg.go:1086 +0x78
panic({0x97d480, 0xc000078270})
        /usr/lib/go/src/runtime/panic.go:884 +0x212
cmd/go/internal/load.ImportErrorf({0x7ffd42211a7e, 0x56}, {0xa2f4ae?, 0x56?}, {0xc00016d630?, 0xc00016db18?, 0x0?})
        /usr/lib/go/src/cmd/go/internal/load/pkg.go:523 +0x199
cmd/go/internal/load.(*Package).load(0xc00033c580, {0xb2e7d0, 0xc000120000}, {0x0, 0x0, 0x0, 0x1, 0x0, 0x0}, {0x7ffd42211a7e, ...}, ...)
        /usr/lib/go/src/cmd/go/internal/load/pkg.go:1894 +0x147d
cmd/go/internal/load.loadImport({0xb2e7d0, 0xc000120000}, {0x0, 0x0, 0x0, 0x1, 0x0, 0x0}, 0xc000383b50, {0x7ffd42211a7e, ...}, ...)
        /usr/lib/go/src/cmd/go/internal/load/pkg.go:744 +0x570
cmd/go/internal/load.PackagesAndErrors({0xb2e7d0?, 0xc000120000?}, {0x0, 0x0, 0x0, 0x1, 0x0, 0x0}, {0xc000136050, 0x6, ...})
        /usr/lib/go/src/cmd/go/internal/load/pkg.go:2794 +0x87b
cmd/go/internal/work.runBuild({0xb2e7d0, 0xc000120000}, 0xc0001523a8?, {0xc000136050, 0x6, 0x6})
        /usr/lib/go/src/cmd/go/internal/work/build.go:408 +0xba
main.invoke(0xe298e0, {0xc000136010, 0xa, 0xa})
        /usr/lib/go/src/cmd/go/main.go:225 +0x34e
main.main()
        /usr/lib/go/src/cmd/go/main.go:179 +0x7d1
make: *** [Makefile:113: yay] Fehler 2
==> FEHLER: Ein Fehler geschah in build().
    Breche ab...
```

**Comment by Jguer** [comment]
`yay-git` should be buildable again and a new patch release of yay is being tailored with just this fix.

Seems some package upgrade caused the condition to pipe the output to the go command

**Comment by Jguer** [comment]
yay v11.3.2 should have the fix for this as well. 

Please report if it is not resolved and thanks for the initial report @OptixWolf

**Comment by abisalde** [comment]
- #Failed to build yay on first install 

![Screenshot from 2023-02-06 20-50-32](https://user-images.githubusercontent.com/38655623/217082762-4f781a95-3304-4699-9e60-caf4e992dd78.png)

**Comment by kido5217** [comment]
@abisalde do you have `base-devel` installed?

```sh
pacman -S --needed git base-devel
```

**Comment by abisalde** [comment]
> @abisalde do you have `base-devel` installed?
> 
> ```shell
> pacman -S --needed git base-devel
> ```

I will try this now

**Comment by chiboreache** [comment]
too much bleeding edge..

```sh
# github.com/Jguer/aur/metadata
../gopath/pkg/mod/github.com/!jguer/aur@v1.2.3/metadata/cache.go:137:28: error: reference to undefined identifier 'url.JoinPath'
137 |         reqURL, err := url.JoinPath(a.baseURL, endpoint)
|                            ^
note: module requires Go 1.19
make: *** [Makefile:113: yay] Error 2
==> ERROR: A failure occurred in build().
Aborting...
➜  yay git:(master) go version
go version go1.18 gccgo (GCC) 12.2.1 20230201 linux/amd64
➜  yay git:(master)
```
