### ISSUE TITLE
interface conversion: interface {} is *alpm.Package, not aur.Pkg

### ISSUE THREAD

**Issue by aimixess** [Jguer/yay#2125]
### Affected Version

🮡-❯❯ yay --version
yay v12.0.4 - libalpm v13.0.2

### Describe the bug
Hello,

When I search package "amd" or "rocm" with yay, it throw me this error :

```
 -> interface conversion: interface {} is *alpm.Package, not aur.Pkg
goroutine 1 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	runtime/debug/stack.go:16 +0x19
main.main.func2()
	github.com/Jguer/yay/v12/main.go:155 +0x5a
panic({0x555e414a95c0, 0xc0001b80c0})
	runtime/panic.go:884 +0x213
github.com/Jguer/yay/v12/pkg/query.(*SourceQueryBuilder).Results(0xc0001d80e0, {0x555e41515148, 0xc0000fc240}, 0x1)
	github.com/Jguer/yay/v12/pkg/query/query_builder.go:215 +0x4b0
main.syncSearch({0x555e41511028?, 0xc00002e148?}, {0xc00019cd00, 0x1, 0x1}, {0x555e41515148, 0xc0000fc240}, {0x555e415111e8, 0xc0001d80e0}, 0x1)
	github.com/Jguer/yay/v12/query.go:32 +0xc9
main.handleSync({0x555e41511028, 0xc00002e148}, 0xc0000c0d80, 0xc0001b9bf0, {0x555e41515148, 0xc0000fc240})
	github.com/Jguer/yay/v12/cmd.go:354 +0xb78
main.handleCmd({0x555e41511028, 0xc00002e148}, 0xc0000c0d80, 0xc0001b9bf0, {0x555e41515148?, 0xc0000fc240?})
	github.com/Jguer/yay/v12/cmd.go:178 +0x36b
main.main()
	github.com/Jguer/yay/v12/main.go:161 +0x9ea
```
### Reproduction Steps

1. yay -Ss amd
2. Reinstall yay manually, same result

### Expected behavior

List of the package containing the "amd" string.

### Output

Output with debug enabled is the same.

**Comment by Jguer** [comment]
Hey @aimixess can you share your `yay -Pg`? Can't reproduce it with either query builder

**Comment by aimixess** [comment]
Hi Jguer,

Here is the result: 
``` 🮡-❯❯ yay -Pg
{
	"aururl": "https://aur.archlinux.org",
	"aurrpcurl": "https://aur.archlinux.org/rpc?",
	"buildDir": "/home/alex/.cache/yay",
	"editor": "",
	"editorflags": "",
	"makepkgbin": "makepkg",
	"makepkgconf": "",
	"pacmanbin": "pacman",
	"pacmanconf": "/etc/pacman.conf",
	"redownload": "no",
	"rebuild": "no",
	"answerclean": "",
	"answerdiff": "",
	"answeredit": "",
	"answerupgrade": "",
	"gitbin": "git",
	"gpgbin": "gpg",
	"gpgflags": "",
	"mflags": "",
	"sortby": "votes",
	"searchby": "name-desc",
	"gitflags": "",
	"removemake": "ask",
	"sudobin": "sudo",
	"sudoflags": "",
	"version": "12.0.4",
	"requestsplitn": 150,
	"completionrefreshtime": 7,
	"maxconcurrentdownloads": 0,
	"bottomup": true,
	"sudoloop": false,
	"timeupdate": false,
	"devel": false,
	"cleanAfter": false,
	"provides": true,
	"pgpfetch": true,
	"upgrademenu": true,
	"cleanmenu": true,
	"diffmenu": true,
	"editmenu": false,
	"combinedupgrade": true,
	"useask": false,
	"batchinstall": false,
	"singlelineresults": false,
	"separatesources": true,
	"newinstallengine": true,
	"debug": false,
	"rpc": true,
	"doubleconfirm": true
}```

**Comment by aimixess** [comment]
I just find the cause of the issue.

These lines in my pacman.conf : 
```
[aur]
SigLevel = PackageOptional DatabaseOptional
Server = file:///var/lib/repo/aur
```
It was probably created by paru and seems to be a problem for yay.

**Comment by Jguer** [comment]
I see the issue, it's the naming of the DB. `yay` assumes `aur` is coming from actually `aur` (ex: `yay -S aur/yay`). I'll see if I can write some safeguards around this.

As a workaround, if you want to use that repo, it should be possible to just rename it
```
[aur_sync]
SigLevel = PackageOptional DatabaseOptional
Server = file:///var/lib/repo/aur
```

**Comment by aimixess** [comment]
Ok, for the moment I removed it.
Thanks for you time and the explanations.
