### ISSUE TITLE
yay fails to build

### ISSUE THREAD

**Issue by Photon89** [Jguer/yay#2173]
### Affected Version

12.0.4 git

### Describe the bug

Building fails with error output (both yay and yay-git).

### Reproduction Steps

1. Try to build the newest yay version
2. Observe the build error

### Expected behavior

A build without error

### Output

```sh
  -> Cloning yay git repo...
Cloning into bare repository '/home/photon/.cache/yay/yay-git/yay'...
remote: Enumerating objects: 13718, done.
remote: Counting objects: 100% (663/663), done.
remote: Compressing objects: 100% (253/253), done.
remote: Total 13718 (delta 418), reused 639 (delta 407), pack-reused 13055
Receiving objects: 100% (13718/13718), 8.30 MiB | 4.99 MiB/s, done.
Resolving deltas: 100% (8720/8720), done.
==> Validating source files with sha256sums...
    yay ... Skipped
==> Making package: yay-git 12.0.4.r0.g26c9ab5-1 (Sat May 20 15:45:23 2023)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating yay git repo...
==> Validating source files with sha256sums...
    yay ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of yay git repo...
Cloning into 'yay'...
done.
Switched to a new branch 'makepkg'
==> Starting pkgver()...
==> Updated version: yay-git 12.0.4.r23.gec15a5b-1
==> Sources are ready.
==> Making package: yay-git 12.0.4.r23.gec15a5b-1 (Sat May 20 15:45:28 2023)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting pkgver()...
==> Starting build()...
go build -trimpath -mod=readonly -modcacherw  -ldflags '-X "main.yayVersion=12.0.4.r23.gec15a5b" -X "main.localePath=/usr/share/locale/" -linkmode=external' -buildmode=pie -o yay
unexpected fault address 0xc0001b47f0
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0xc0001b47f0 pc=0xc0001b47f0]

goroutine 1 [running]:
runtime.throw({0xa447c6?, 0x9991e0?})
	/usr/lib/go/src/runtime/panic.go:1047 +0x5d fp=0xc00019f218 sp=0xc00019f1e8 pc=0x436bfd
runtime: g 1: unexpected return pc for runtime.sigpanic called from 0xc0001b47f0
stack: frame={sp:0xc00019f218, fp:0xc00019f278} stack=[0xc00019c000,0xc0001a0000)
0x000000c00019f118:  0x000000000045803b <runtime.write+0x000000000000003b>  0x0000000000000002 
0x000000c00019f128:  0x000000c00019f160  0x000000000043850e <runtime.recordForPanic+0x000000000000004e> 
0x000000c00019f138:  0x000000000045803b <runtime.write+0x000000000000003b>  0x0000000000000002 
0x000000c00019f148:  0x0000000000b3bc08  0x0000000000000001 
0x000000c00019f158:  0x0000000000000001  0x000000c00019f198 
0x000000c00019f168:  0x0000000000438812 <runtime.gwrite+0x00000000000000f2>  0x0000000000b3bc08 
0x000000c00019f178:  0x0000000000000001  0x0000000000000001 
0x000000c00019f188:  0x000000c00019f1fc  0x000000000000000c 
0x000000c00019f198:  0x0000000000466e6e <runtime.systemstack+0x000000000000002e>  0x0000000000436f4c <runtime.fatalthrow+0x000000000000006c> 
0x000000c00019f1a8:  0x000000c00019f1b8  0x000000c0000061a0 
0x000000c00019f1b8:  0x0000000000436f80 <runtime.fatalthrow.func1+0x0000000000000000>  0x000000c0000061a0 
0x000000c00019f1c8:  0x0000000000436bfd <runtime.throw+0x000000000000005d>  0x000000c00019f1e8 
0x000000c00019f1d8:  0x000000c00019f208  0x0000000000436bfd <runtime.throw+0x000000000000005d> 
0x000000c00019f1e8:  0x000000c00019f1f0  0x0000000000436c20 <runtime.throw.func1+0x0000000000000000> 
0x000000c00019f1f8:  0x0000000000a447c6  0x0000000000000005 
0x000000c00019f208:  0x000000c00019f268  0x000000000044cf0a <runtime.sigpanic+0x000000000000028a> 
0x000000c00019f218: <0x0000000000a447c6  0x00000000009991e0 
0x000000c00019f228:  0x000000c0001b47f0  0x0200000000984dc0 
0x000000c00019f238:  0x0000000000000018  0x0000000000b45938 
0x000000c00019f248:  0x000000c0000061a0  0x000000c00002c6a8 
0x000000c00019f258:  0x000000c0001a4000  0x000000c000028158 
0x000000c00019f268:  0x000000000019f250 !0x000000c0001b47f0 
0x000000c00019f278: >0x000000c00019f290  0x000000c0001b47d0 
0x000000c00019f288:  0x00000000009991e0  0x000000000082bce0 <cmd/go/internal/modload.(*loader).pkg.func1+0x0000000000000000> 
0x000000c00019f298:  0x000000c00002c6a8  0x0000000000000018 
0x000000c00019f2a8:  0x000000c0001a4000  0x0000000000b45938 
0x000000c00019f2b8:  0x000000c000028158  0x0000000000000002 
0x000000c00019f2c8:  0x000000c00019f6c8  0x0000000000829577 <cmd/go/internal/modload.loadFromRoots+0x00000000000009f7> 
0x000000c00019f2d8:  0x000000c0001a4000  0x0000000000b45938 
0x000000c00019f2e8:  0x000000c000028158  0x000000c00002c6a8 
0x000000c00019f2f8:  0x0000000000000018  0x0000000000817c02 <cmd/go/internal/modload.(*MainModuleSet).Index+0x0000000000000122> 
0x000000c00019f308:  0x000000c00019f388  0x000000c00019f370 
0x000000c00019f318:  0x0000000000817bb2 <cmd/go/internal/modload.(*MainModuleSet).Index+0x00000000000000d2>  0x00000000009b6fc0 
0x000000c00019f328:  0x000000c000182db0  0x000000c0000b6300 
0x000000c00019f338:  0x0000000000000000  0x0000000000000001 
0x000000c00019f348:  0x0000000000000000  0x0000000000000000 
0x000000c00019f358:  0x0000000000817c20 <cmd/go/internal/modload.(*MainModuleSet).Index.func1+0x0000000000000000>  0x000000c0000e6348 
0x000000c00019f368:  0x000000c00019f358  0x000000c00019f6c8 
runtime.sigpanic()
	/usr/lib/go/src/runtime/signal_unix.go:851 +0x28a fp=0xc00019f278 sp=0xc00019f218 pc=0x44cf0a

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/lib/go/src/runtime/proc.go:381 +0xd6 fp=0xc000054fb0 sp=0xc000054f90 pc=0x439916
runtime.goparkunlock(...)
	/usr/lib/go/src/runtime/proc.go:387
runtime.forcegchelper()
	/usr/lib/go/src/runtime/proc.go:305 +0xb0 fp=0xc000054fe0 sp=0xc000054fb0 pc=0x439750
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000054fe8 sp=0xc000054fe0 pc=0x469041
created by runtime.init.6
	/usr/lib/go/src/runtime/proc.go:293 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/lib/go/src/runtime/proc.go:381 +0xd6 fp=0xc000055780 sp=0xc000055760 pc=0x439916
runtime.goparkunlock(...)
	/usr/lib/go/src/runtime/proc.go:387
runtime.bgsweep(0x0?)
	/usr/lib/go/src/runtime/mgcsweep.go:278 +0x8e fp=0xc0000557c8 sp=0xc000055780 pc=0x425b2e
runtime.gcenable.func1()
	/usr/lib/go/src/runtime/mgc.go:178 +0x26 fp=0xc0000557e0 sp=0xc0000557c8 pc=0x41ade6
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000557e8 sp=0xc0000557e0 pc=0x469041
created by runtime.gcenable
	/usr/lib/go/src/runtime/mgc.go:178 +0x6b

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc0000320e0?, 0xb3bb38?, 0x1?, 0x0?, 0x0?)
	/usr/lib/go/src/runtime/proc.go:381 +0xd6 fp=0xc000055f70 sp=0xc000055f50 pc=0x439916
runtime.goparkunlock(...)
	/usr/lib/go/src/runtime/proc.go:387
runtime.(*scavengerState).park(0xe689c0)
	/usr/lib/go/src/runtime/mgcscavenge.go:400 +0x53 fp=0xc000055fa0 sp=0xc000055f70 pc=0x423a53
runtime.bgscavenge(0x0?)
	/usr/lib/go/src/runtime/mgcscavenge.go:628 +0x45 fp=0xc000055fc8 sp=0xc000055fa0 pc=0x424025
runtime.gcenable.func2()
	/usr/lib/go/src/runtime/mgc.go:179 +0x26 fp=0xc000055fe0 sp=0xc000055fc8 pc=0x41ad86
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000055fe8 sp=0xc000055fe0 pc=0x469041
created by runtime.gcenable
	/usr/lib/go/src/runtime/mgc.go:179 +0xaa

goroutine 5 [finalizer wait]:
runtime.gopark(0x1a0?, 0xe6a180?, 0x60?, 0x78?, 0xc000054770?)
	/usr/lib/go/src/runtime/proc.go:381 +0xd6 fp=0xc000054628 sp=0xc000054608 pc=0x439916
runtime.runfinq()
	/usr/lib/go/src/runtime/mfinal.go:193 +0x107 fp=0xc0000547e0 sp=0xc000054628 pc=0x419e27
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000547e8 sp=0xc0000547e0 pc=0x469041
created by runtime.createfing
	/usr/lib/go/src/runtime/mfinal.go:163 +0x45

goroutine 6 [runnable]:
syscall.Syscall(0x7f7edce69ab8?, 0x7f7f06c32f18?, 0x60?, 0xc000058c00?)
	/usr/lib/go/src/syscall/syscall_linux.go:69 +0x27 fp=0xc000096f90 sp=0xc000096f20 pc=0x480467
syscall.fcntl(0x40f627?, 0x58?, 0xa18ce0?)
	/usr/lib/go/src/syscall/zsyscall_linux_amd64.go:407 +0x2b fp=0xc000096fc8 sp=0xc000096f90 pc=0x47de0b
syscall.SetNonblock(0x0?, 0x1)
	/usr/lib/go/src/syscall/exec_unix.go:107 +0x29 fp=0xc000096ff8 sp=0xc000096fc8 pc=0x4786a9
os.newFile(0x4, {0xc00002a064, 0x27}, 0x1)
	/usr/lib/go/src/os/file_unix.go:175 +0x125 fp=0xc000097038 sp=0xc000096ff8 pc=0x4ec665
os.openFileNolog({0xc00002a064, 0x27}, 0x0, 0x0)
	/usr/lib/go/src/os/file_unix.go:250 +0x17a fp=0xc000097080 sp=0xc000097038 pc=0x4ec8fa
os.OpenFile({0xc00002a064, 0x27}, 0x0, 0x418d2d?)
	/usr/lib/go/src/os/file.go:326 +0x45 fp=0xc0000970b8 sp=0xc000097080 pc=0x4ea645
os.Open(...)
	/usr/lib/go/src/os/file.go:306
os.ReadDir({0xc00002a064?, 0xc00002a064?})
	/usr/lib/go/src/os/dir.go:116 +0x65 fp=0xc000097178 sp=0xc0000970b8 pc=0x4e6345
cmd/go/internal/fsys.readDir({0xc00002a064, 0x27})
	/usr/lib/go/src/cmd/go/internal/fsys/fsys.go:302 +0x3b fp=0xc000097220 sp=0xc000097178 pc=0x5a883b
cmd/go/internal/fsys.ReadDir({0xc00002a064, 0x27})
	/usr/lib/go/src/cmd/go/internal/fsys/fsys.go:335 +0x2be fp=0xc0000975b0 sp=0xc000097220 pc=0x5a8dbe
cmd/go/internal/modindex.dirHash({0xc00002a064, 0x27}, {0xc00002a064, 0x27})
	/usr/lib/go/src/cmd/go/internal/modindex/read.go:89 +0x1a8 fp=0xc0000976d8 sp=0xc0000975b0 pc=0x7f0108
cmd/go/internal/modindex.openIndexPackage.func1()
	/usr/lib/go/src/cmd/go/internal/modindex/read.go:217 +0x85 fp=0xc0000977e0 sp=0xc0000976d8 pc=0x7f0e05
cmd/go/internal/par.(*Cache).Do(0xe67e40, {0x99c420, 0xc000110020}, 0xc000062868)
	/usr/lib/go/src/cmd/go/internal/par/work.go:128 +0xc3 fp=0xc000097828 sp=0xc0000977e0 pc=0x5cd143
cmd/go/internal/modindex.openIndexPackage({0xc00002a064, 0x27}, {0xc00002a064, 0x27})
	/usr/lib/go/src/cmd/go/internal/modindex/read.go:215 +0xd0 fp=0xc0000978a0 sp=0xc000097828 pc=0x7f0d10
cmd/go/internal/modindex.GetPackage({0xc00002a064, 0x27}, {0xc00002a064, 0x27})
	/usr/lib/go/src/cmd/go/internal/modindex/read.go:144 +0x156 fp=0xc0000978e8 sp=0xc0000978a0 pc=0x7f05d6
cmd/go/internal/modload.dirInModule.func2()
	/usr/lib/go/src/cmd/go/internal/modload/import.go:685 +0x35 fp=0xc000097948 sp=0xc0000978e8 pc=0x817255
cmd/go/internal/par.(*Cache).Do(0xe67e60, {0x9991e0, 0xc00010e000}, 0xc000062a30)
	/usr/lib/go/src/cmd/go/internal/par/work.go:128 +0xc3 fp=0xc000097990 sp=0xc000097948 pc=0x5cd143
cmd/go/internal/modload.dirInModule({0xc00002c6a8, 0x18}, {0xc00002c6a8?, 0x18}, {0xc00002a064, 0x27}, 0x1)
	/usr/lib/go/src/cmd/go/internal/modload/import.go:681 +0x2c8 fp=0xc000097a60 sp=0xc000097990 pc=0x817028
cmd/go/internal/modload.importFromModules({0xb45938, 0xc000028158}, {0xc00002c6a8, 0x18}, 0xc0000882d0, 0x0)
	/usr/lib/go/src/cmd/go/internal/modload/import.go:401 +0x1878 fp=0xc000097e40 sp=0xc000097a60 pc=0x814498
cmd/go/internal/modload.(*loader).load(0xc0001a4000, {0xb45938, 0xc000028158}, 0xc0001abad0)
	/usr/lib/go/src/cmd/go/internal/modload/load.go:1700 +0xa9 fp=0xc000097f30 sp=0xc000097e40 pc=0x82cda9
cmd/go/internal/modload.(*loader).pkg.func1.1()
	/usr/lib/go/src/cmd/go/internal/modload/load.go:1513 +0x29 fp=0xc000097f60 sp=0xc000097f30 pc=0x82be69
cmd/go/internal/par.(*Queue).Add.func1()
	/usr/lib/go/src/cmd/go/internal/par/queue.go:58 +0x5f fp=0xc000097fe0 sp=0xc000097f60 pc=0x5cc87f
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000097fe8 sp=0xc000097fe0 pc=0x469041
created by cmd/go/internal/par.(*Queue).Add
	/usr/lib/go/src/cmd/go/internal/par/queue.go:56 +0x1df
make: *** [Makefile:113: yay] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: yay-git
```

**Comment by Jguer** [comment]
Hey @Photon89, are you using gcc-go?

**Comment by Photon89** [comment]
@Jguer Nope, it's not installed. Is it a new build dependency?

**Comment by Jguer** [comment]
No, gcc-go is known to cause errors due to an outdated go implementation.

Can you give me the output of 

`pacman -T base-devel` and `go version`

**Comment by Photon89** [comment]
Sure!

```
$ pacman -T base-devel
base-devel

$ go version
go version go1.20.4 linux/amd64
```

**Comment by Jguer** [comment]
try `sudo pacman -S base-devel` seems you're missing the meta package (it's a pre-requirement for using the AUR)

**Comment by Photon89** [comment]
I absolutely don't understand, how base-devel got removed...  I installed it now:

```
$ grep base-devel /var/log/pacman.log 
[2012-05-17 23:42] Running 'pacman -S base-devel'
[2012-07-28 10:15] Running 'pacman -S base-devel'
[2023-05-23T20:00:43+0200] [PACMAN] Running 'pacman -S --config /etc/pacman.conf -- base-devel'
[2023-05-23T20:00:44+0200] [ALPM] installed base-devel (1-1)
```

However, I still get the identical error message when trying to update yay...

**Comment by Photon89** [comment]
For some reason I could run the update to 1.2.0.5 today (though the same version didn't build earlier). No idea what went wrong, the problem is solved for me though!
