### ISSUE TITLE
Parsing SRCINFO: unsupported arch "armv6h"

### ISSUE THREAD

**Issue by happyme531** [Jguer/yay#2488]
### Affected Version

yay v12.3.5 - libalpm v14.0.0

### Reproduction Steps

1. yay -S v2raya-bin

### Output

```sh
 ~> yay -S v2raya-bin --debug
[DEBUG:runtime] packages to query [v2raya-bin]
[DEBUG:runtime] rpc request https://aur.archlinux.org/rpc?arg%5B%5D=v2raya-bin&type=info&v=5
[DEBUG:grapher] v2raya-bin provides: v2raya
AUR Explicit (1): v2raya-bin-2.2.5.8-1
[DEBUG:runner] capturing /usr/bin/git -C /home/user/.cache/yay/v2raya-bin pull --rebase --autostash
:: (1/1) Downloaded PKGBUILD: v2raya-bin
[DEBUG:runner] capturing /usr/bin/git -C /home/user/.cache/yay/v2raya-bin reset --hard HEAD
[DEBUG:runner] capturing /usr/bin/git -C /home/user/.cache/yay/v2raya-bin merge --no-edit --ff
[DEBUG:db] populating db executor package caches. sync_len 2692 remote_len 230
  1 v2raya-bin                       (Installed) (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
  1 v2raya-bin                       (Installed) (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
[DEBUG:runner] running /usr/bin/makepkg --verifysource --skippgpcheck -f -Cc
==> Making package: v2raya-bin 2.2.5.8-1 (2024年08月12日 星期一 22时48分05秒)
==> Retrieving sources...
  -> Found v2raya.service
  -> Found v2raya-lite.service
  -> Found v2raya.png
  -> Found v2raya.desktop
  -> Found v2raya_2.2.5.8
==> WARNING: Skipping verification of source file PGP signatures.
==> Validating source files with sha1sums...
    v2raya.service ... Passed
    v2raya-lite.service ... Passed
    v2raya.png ... Passed
    v2raya.desktop ... Passed
==> Validating source_x86_64 files with sha1sums...
    v2raya_2.2.5.8 ... Passed
:: (1/1) Parsing SRCINFO: v2raya-bin
 -> failed to parse v2raya-bin: Line 31: Invalid key "sha1sums_armv6h" unsupported arch "armv6h": sha1sums_armv6h = {{sha1sums_armv6h}}goroutine 1 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x5e
main.main.func2()
        github.com/Jguer/yay/v12/main.go:125 +0x45
panic({0x564fedccbaa0?, 0xc0002820f0?})
        runtime/panic.go:770 +0x132
github.com/Jguer/yay/v12/pkg/sync/srcinfo.NewService({0x564fedd4c4d0, 0xc0001be240}, 0xc0001d6200, 0xc0004121e0, {0x564fedd49e58, 0xc000184480}, {0x564fedd48e30, 0xc000025880}, 0xc0003023f0)
        github.com/Jguer/yay/v12/pkg/sync/srcinfo/service.go:37 +0x1c7
github.com/Jguer/yay/v12/pkg/sync.(*OperationService).Run(0xc0003021e0, {0x564fedd47c30, 0x564fee040c00}, 0xc0001b7420, 0xc0001e1da0, {0xc00007c968, 0x1, 0x1}, {0x564fee040c00, 0x0, ...})
        github.com/Jguer/yay/v12/pkg/sync/sync.go:74 +0xdbf
main.syncInstall({0x564fedd47c30, 0x564fee040c00}, 0xc0001b7420, 0xc0001e1da0, {0x564fedd4c4d0, 0xc0001be240})
        github.com/Jguer/yay/v12/sync.go:90 +0xf31
main.handleSync({0x564fedd47c30, 0x564fee040c00}, 0xc0001b7420, 0xc0001e1da0, {0x564fedd4c4d0, 0xc0001be240})
        github.com/Jguer/yay/v12/cmd.go:358 +0x91f
main.handleCmd({0x564fedd47c30, 0x564fee040c00}, 0xc0001b7420, 0xc0001e1da0, {0x564fedd4c4d0, 0xc0001be240})
        github.com/Jguer/yay/v12/cmd.go:167 +0x345
main.main()
        github.com/Jguer/yay/v12/main.go:131 +0x69f

```

**Comment by v613** [comment]
It seems that the issues you are experiencing might be related to the PKGBUILD file, based on the comments in the AUR repository <br>https://aur.archlinux.org/packages/v2raya-bin#comment-989435

It appears that the problems are specific to the AUR repository, as the PKGBUILD there differs from the one in the Git repository
https://github.com/v2rayA/v2rayA/pull/1449#issuecomment-2230302441

Removed in <br>
- https://aur.archlinux.org/cgit/aur.git/commit/?h=v2raya-bin&id=c3399d5659dcced42c8d99cdbfa358adf476ddfc

Added back in
- https://aur.archlinux.org/cgit/aur.git/commit/?h=v2raya-bin&id=34c8e4c270b51cb92b7396cec3b5b0856c558aaa
- https://aur.archlinux.org/cgit/aur.git/commit/?h=v2raya-bin&id=f9a69b9e7eb955c601c2ff8e677e8814157793a9
