### ISSUE TITLE
`yay -Y --gendb` crashes with SIGSEGV

### ISSUE THREAD

**Issue by xaverh** [Jguer/yay#310]
#### Affected Version
yay v5.608

#### Issue
`yay -Y --gendb` crashes with SIGSEGV

#### Steps to reproduce
```
$ yay -Y --gendb
==> Out Of Date AUR Packages: spotify
:: PKGBUILD up to date, Skipping (1/23): brave-bin
:: PKGBUILD up to date, Skipping (2/23): clipmenu
:: PKGBUILD up to date, Skipping (3/23): clipnotify
:: PKGBUILD up to date, Skipping (4/23): conan
:: PKGBUILD up to date, Skipping (5/23): dwm
:: PKGBUILD up to date, Skipping (6/23): ffmpeg-compat-54
:: PKGBUILD up to date, Skipping (7/23): google-chrome-beta
:: PKGBUILD up to date, Skipping (8/23): libavutil-52
:: PKGBUILD up to date, Skipping (9/23): libgcj17-bin
:: PKGBUILD up to date, Skipping (10/23): mons
:: PKGBUILD up to date, Skipping (11/23): openvpn-update-systemd-resolved
:: PKGBUILD up to date, Skipping (12/23): pdftk-bin
:: PKGBUILD up to date, Skipping (13/23): python-node-semver
:: PKGBUILD up to date, Skipping (14/23): python-patch
:: PKGBUILD up to date, Skipping (15/23): python-pluginbase
:: PKGBUILD up to date, Skipping (16/23): simple-mtpfs
:: PKGBUILD up to date, Skipping (17/23): spotify
:: PKGBUILD up to date, Skipping (18/23): st
:: PKGBUILD up to date, Skipping (19/23): tresorit
:: PKGBUILD up to date, Skipping (20/23): ttf-input
:: PKGBUILD up to date, Skipping (21/23): visual-studio-code-bin
:: Downloading PKGBUILD (22/23): wire-desktop-bin
:: PKGBUILD up to date, Skipping (23/23): yay
:: Parsing SRCINFO (1/23): brave-bin
:: Parsing SRCINFO (2/23): clipmenu
:: Parsing SRCINFO (3/23): clipnotify
:: Parsing SRCINFO (4/23): conan
:: Parsing SRCINFO (5/23): dwm
:: Parsing SRCINFO (6/23): ffmpeg-compat-54
:: Parsing SRCINFO (7/23): google-chrome-beta
:: Parsing SRCINFO (8/23): libavutil-52
:: Parsing SRCINFO (9/23): libgcj17-bin
:: Parsing SRCINFO (10/23): mons
:: Parsing SRCINFO (11/23): openvpn-update-systemd-resolved
:: Parsing SRCINFO (12/23): pdftk-bin
:: Parsing SRCINFO (13/23): python-node-semver
:: Parsing SRCINFO (14/23): python-patch
:: Parsing SRCINFO (15/23): python-pluginbase
:: Parsing SRCINFO (16/23): simple-mtpfs
:: Parsing SRCINFO (17/23): spotify
:: Parsing SRCINFO (18/23): st
:: Parsing SRCINFO (19/23): tresorit
:: Parsing SRCINFO (20/23): ttf-input
:: Parsing SRCINFO (21/23): visual-studio-code-bin
:: Parsing SRCINFO (22/23): wire-desktop-bin
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1c0 pc=0x6636ba]

goroutine 1 [running]:
main.createDevelDB(0xc420090de0, 0xc420057d08)
        /home/xha/.cache/yay/yay/src/yay-5.608/vcs.go:53 +0x30a
main.handleYay(0xc4200a2430, 0x1)
        /home/xha/.cache/yay/yay/src/yay-5.608/cmd.go:290 +0xf0
main.handleCmd(0x0, 0x0)
        /home/xha/.cache/yay/yay/src/yay-5.608/cmd.go:155 +0x444
main.main()
        /home/xha/.cache/yay/yay/src/yay-5.608/main.go:204 +0x253
```

**Comment by Morganamilo** [comment]
The .SRCINFO for `wire-desktop-bin` is malformed. Note the broken indentation on the pkgver. This is their problem mostly. Although we should beadle to print its malformed and skip it instead of crashing.

**Comment by Jguer** [comment]
Good bisection, let's just try and skip instead of crashing
