### ISSUE TITLE
Runtime error when trying to install a package

### ISSUE THREAD

**Issue by Fandekasp** [Jguer/yay#424]
#### Affected Version

yay v6.727

#### Issue
When running yay -Syu yesterday, a conflict occured between xorg-server and xf86-video-intel-git, and following yay's suggestion, I deleted the latter.
This morning, I noticed that my external monitor would keep a black screen although i3 and xrandr seem to understand the monitor is there, so I tried reinstalling xf86-video-intel-git. That's when the error occured.

#### Steps to reproduce

```
$ yay -S xf86-video-intel-git 
:: Querying AUR...
panic: runtime error: index out of range

goroutine 1 [running]:
main.checkVersions(0xc4200a7180, 0xc42005d0a8, 0x2)
        /home/dori/.cache/yay/yay/src/yay-6.727/dependencies.go:565 +0x105d
main.getDepTree(0xc42008cdb0, 0x1, 0x1, 0xc4200a4550, 0x0, 0x80, 0xc4201d6a80)
        /home/dori/.cache/yay/yay/src/yay-6.727/dependencies.go:397 +0x79a
main.install(0xc42008ede0, 0xc42005dc58, 0x2)
        /home/dori/.cache/yay/yay/src/yay-6.727/install.go:64 +0x296
main.handleSync(0xc4200a0430, 0x1)
        /home/dori/.cache/yay/yay/src/yay-6.727/cmd.go:403 +0x47b
main.handleCmd(0x0, 0x0)
        /home/dori/.cache/yay/yay/src/yay-6.727/cmd.go:166 +0x51f
main.main()
        /home/dori/.cache/yay/yay/src/yay-6.727/main.go:211 +0x253

$ yay -Sc   
[sudo] password for dori:
Packages to keep:
  All locally installed packages

Cache directory: /var/cache/pacman/pkg/
:: Do you want to remove all other packages from cache? [Y/n] 
removing old packages from cache...

Database directory: /var/lib/pacman/
:: Do you want to remove unused repositories? [Y/n] 
removing unused sync repositories...

Build directory: /home/dori/.cache/yay/
==> Do you want to remove all other AUR packages from cache? [Y/n] 
removing AUR packages from cache...
==> Do you want to remove ALL untracked AUR files? [Y/n] 
removing Untracked AUR files from cache...

$ yay -S xf86-video-intel-git  
:: Querying AUR...
panic: runtime error: index out of range

goroutine 1 [running]:
main.checkVersions(0xc4200a7180, 0xc42005d0a8, 0x2)
        /home/dori/.cache/yay/yay/src/yay-6.727/dependencies.go:565 +0x105d
main.getDepTree(0xc42008cdb0, 0x1, 0x1, 0xc4200a4550, 0x0, 0x80, 0xc4201d6a80)
        /home/dori/.cache/yay/yay/src/yay-6.727/dependencies.go:397 +0x79a
main.install(0xc42008ede0, 0xc42005dc58, 0x2)
        /home/dori/.cache/yay/yay/src/yay-6.727/install.go:64 +0x296
main.handleSync(0xc4200a0430, 0x1)
        /home/dori/.cache/yay/yay/src/yay-6.727/cmd.go:403 +0x47b
main.handleCmd(0x0, 0x0)
        /home/dori/.cache/yay/yay/src/yay-6.727/cmd.go:166 +0x51f
main.main()
        /home/dori/.cache/yay/yay/src/yay-6.727/main.go:211 +0x253

```

**Comment by Morganamilo** [comment]
Should be fixed in -git.

**Comment by Fandekasp** [comment]
@Morganamilo thanks for the quick follow-up

Installed yay-git, then retried. Getting another error now
```
➜ yay -S xf86-video-intel-git     
:: Querying AUR...
 -> Missing AUR Packages:  X-ABI-VIDEODRV_VERSION
==> Error: Could not find all required packages:
    X-ABI-VIDEODRV_VERSION
    X-ABI-VIDEODRV_VERSION>=23 X-ABI-VIDEODRV_VERSION<=23

➜ yay -V        
yay v6.727.r46.g6be6ffc
```

**Comment by Morganamilo** [comment]
Looks like another problem with the version checking. Should be all fixed in #401. For now `yay -Sd  xf86-video-intel-git` should hopefully work.

**Comment by Fandekasp** [comment]
@Morganamilo 
```
$ yay -Sd xf86-video-intel-git    
:: Querying AUR...
 -> Missing AUR Packages:  X-ABI-VIDEODRV_VERSION
==> Error: Could not find all required packages:
    X-ABI-VIDEODRV_VERSION
```
I reported it on the [xf86-video-intel-git aur page](https://aur.archlinux.org/packages/xf86-video-intel-git/), looks like this new issue is unrelated to yay. Thank you for the support, I'll close this issue for now.

**Comment by Morganamilo** [comment]
try with makepkg before saying it's unrelated with Yay.

I just tried this myself with Yay and I don't get the error. 

`X-ABI-VIDEODRV_VERSION` is provided by xorg so it shouldn't be missing. I don't know why Yay can't find it.

What does `pacman -Si xorg-server` and `pacman -Qi xorg-server` show.

**Comment by Fandekasp** [comment]
```
makepkg -si                                                                  [11:24:52]
==> Making package: xf86-video-intel-git 1:2.99.917+781+gc8990575-1 (Fri May 18 11:25:21 JST 2018)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Installing missing dependencies...
[sudo] password for dori: 
error: target not found: X-ABI-VIDEODRV_VERSION=23
==> ERROR: 'pacman' failed to install missing dependencies.
```

Basically,  xf86-video-intel-git requires a version of X-ABI-VIDEODRV_VERSION that is older than the one currently provided by xorg-server. I'd have to downgrade xorg-server, so it really looks unrelated to yay :)

**Comment by Morganamilo** [comment]
Yep indeed looks unrelated to Yay. Thanks for testing.

**Comment by Morganamilo** [comment]
>But indeed, it would be helpful if yay could output the same error message

```
==> Error: Could not find all required packages:
    X-ABI-VIDEODRV_VERSION
    X-ABI-VIDEODRV_VERSION>=23 X-ABI-VIDEODRV_VERSION<=23
```

I think is readable enough.

#401 should make is more like this though.

```
==> Error: Could not find all required packages:
    X-ABI-VIDEODRV_VERSION=23
```

**Comment by AladW** [comment]
Maybe it's just me but I find the "package -> " with nothing after the arrow a bit strange... a tree is a graph and in a graph you don't have edges with only 1 vertex either.

**Comment by Morganamilo** [comment]
Well in my head it points, back to `X-ABI-VIDEODRV_VERSION=23`. It's just that it comes first because it's the most important aspect. It's not final anyway so it could change.
