### ISSUE TITLE
Panic on yay pip2pkgbuild

### ISSUE THREAD

**Issue by hrehfeld** [Jguer/yay#70]
```
$ yay pip2pkgbuild
1 aur/pip2pkgbuild 0.2.3-1 (14) 
    Generate PKGBUILD file for a Python module from PyPi
0 aur/python2-pip2pkgbuild 0.2.3-1 (14) 
    Generate PKGBUILD file for a Python module from PyPi
Type numbers to install. Separate each number with a space.
Numbers: 1
==> Installing pip2pkgbuild
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/mikkeloscar/gopkgbuild.parseDependency(0xc4201fe000, 0x0, 0x0, 0x0, 0x0, 0xc4202ce3e0, 0x0, 0x1, 0x0, 0x0)
        /home/hrehfeld/.local/tmp/yaourt-tmp-hrehfeld/aur-yay/src/.go/src/github.com/mikkeloscar/gopkgbuild/pkgbuild.go:450 +0x989
github.com/mikkeloscar/gopkgbuild.parse(0xc4201fe000, 0x270, 0xc4201fe000, 0xa51440, 0x0)
        /home/hrehfeld/.local/tmp/yaourt-tmp-hrehfeld/aur-yay/src/.go/src/github.com/mikkeloscar/gopkgbuild/pkgbuild.go:300 +0x16f6
github.com/mikkeloscar/gopkgbuild.parsePKGBUILD(0xc4201fe000, 0x270, 0x270, 0x470, 0xc4201fe000)
        /home/hrehfeld/.local/tmp/yaourt-tmp-hrehfeld/aur-yay/src/.go/src/github.com/mikkeloscar/gopkgbuild/pkgbuild.go:209 +0x4d
github.com/mikkeloscar/gopkgbuild.ParseSRCINFO(0xc4204fd320, 0x26, 0x1e, 0x6d8080, 0x8)
        /home/hrehfeld/.local/tmp/yaourt-tmp-hrehfeld/aur-yay/src/.go/src/github.com/mikkeloscar/gopkgbuild/pkgbuild.go:204 +0x1b8
main.setupPackageSpace(0xc420509900, 0x22, 0xc420509438, 0x1, 0x1, 0x2c)
        /home/hrehfeld/.local/tmp/yaourt-tmp-hrehfeld/aur-yay/src/yay-2.201/install.go:78 +0x1e3
main.PkgInstall(0xc420509900, 0x0, 0x0, 0x0, 0x1, 0x4, 0x0, 0x0, 0x43)
        /home/hrehfeld/.local/tmp/yaourt-tmp-hrehfeld/aur-yay/src/yay-2.201/install.go:100 +0x116
main.aurInstall(0xc4202ce100, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x1)
        /home/hrehfeld/.local/tmp/yaourt-tmp-hrehfeld/aur-yay/src/yay-2.201/install.go:45 +0x20c
main.numberMenu(0xc42007cb70, 0x1, 0x1, 0x0, 0x0, 0x0, 0x1, 0x1)
        /home/hrehfeld/.local/tmp/yaourt-tmp-hrehfeld/aur-yay/src/yay-2.201/cmd.go:355 +0xb6d
main.main()
        /home/hrehfeld/.local/tmp/yaourt-tmp-hrehfeld/aur-yay/src/yay-2.201/cmd.go:252 +0xbd2
```

yay v2.201

Yaourt works just fine.

**Comment by Morganamilo** [comment]
Fixed upstream in https://github.com/mikkeloscar/gopkgbuild/pull/5

**Comment by Morganamilo** [comment]
This is fixed in master and should be closed.
