### ISSUE TITLE
ctrl-shift-4 on fr-oss layout result in complete crash with a stackstrace

### ISSUE THREAD

**Issue by Porkepix** [Jguer/yay#976]
#### Affected Version
`yay v9.2.1 - libalpm v11.0.3`

#### Issue

1. Run `yay -Syu`
2. If there are packages to upgrade, press control-shift-4
3. yay crashes

Issue happens using fr-oss layout. On a US layout, I could do it with ctrl-shift and the `| \` key.
#### Output
```
==> Packages to not upgrade: (eg: 1 2 3, 1-3, ^4 or repo name)
==> ^\SIGQUIT: quit
PC=0x460041 m=0 sigcode=128

goroutine 0 [idle]:
runtime.futex(0xa3cf48, 0x80, 0x0, 0x0, 0x0, 0x7f0e45764d98, 0x0, 0x0, 0x7fff5b647658, 0x410d61, ...)
	/usr/lib/go/src/runtime/sys_linux_amd64.s:535 +0x21
runtime.futexsleep(0xa3cf48, 0x7fff00000000, 0xffffffffffffffff)
	/usr/lib/go/src/runtime/os_linux.go:46 +0x4b
runtime.notesleep(0xa3cf48)
	/usr/lib/go/src/runtime/lock_futex.go:151 +0xa1
runtime.stopm()
	/usr/lib/go/src/runtime/proc.go:1936 +0xc1
runtime.findrunnable(0xc000020000, 0x0)
	/usr/lib/go/src/runtime/proc.go:2399 +0x54a
runtime.schedule()
	/usr/lib/go/src/runtime/proc.go:2525 +0x21c
runtime.park_m(0xc000406180)
	/usr/lib/go/src/runtime/proc.go:2605 +0xa1
runtime.mcall(0x6e13f0)
	/usr/lib/go/src/runtime/asm_amd64.s:299 +0x5b

goroutine 1 [syscall]:
syscall.Syscall(0x0, 0x0, 0xc0004ca000, 0x1000, 0x43126f, 0x8, 0xc000530040)
	/usr/lib/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0x0, 0xc0004ca000, 0x1000, 0x1000, 0x0, 0x2, 0x0)
	/usr/lib/go/src/syscall/zsyscall_linux_amd64.go:732 +0x5a
syscall.Read(...)
	/usr/lib/go/src/syscall/syscall_unix.go:172
internal/poll.(*FD).Read(0xc00005c060, 0xc0004ca000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go/src/internal/poll/fd_unix.go:165 +0x131
os.(*File).read(...)
	/usr/lib/go/src/os/file_unix.go:263
os.(*File).Read(0xc000010010, 0xc0004ca000, 0x1000, 0x1000, 0x7f0e41d202b8, 0xc00009b340, 0x412189)
	/usr/lib/go/src/os/file.go:108 +0x70
bufio.(*Reader).fill(0xc00009b440)
	/usr/lib/go/src/bufio/bufio.go:100 +0x10f
bufio.(*Reader).ReadSlice(0xc00009b440, 0xa, 0xc00009b348, 0x4b45e2, 0xc00005c0c0, 0x0, 0xc00009b370)
	/usr/lib/go/src/bufio/bufio.go:356 +0x3d
bufio.(*Reader).ReadLine(0xc00009b440, 0x1000, 0x1000, 0xc0004ca000, 0x15, 0xc00009b408, 0x466aea)
	/usr/lib/go/src/bufio/bufio.go:385 +0x34
main.getInput(0x0, 0x0, 0xc00009b638, 0x1, 0x1, 0x15)
	config.go:307 +0x214
main.upgradePkgs(0xc000106180, 0x1, 0x1, 0xc0004ba000, 0x8, 0x8, 0x8, 0x0, 0x0, 0xc00017ee00)
	upgrade.go:353 +0x67a
main.install(0xc00005a3c0, 0x0, 0x0)
	install.go:81 +0x2b99
main.handleSync(0xa14bf3, 0x1)
	cmd.go:272 +0x449
main.handleCmd(0x0, 0x0)
	cmd.go:154 +0x384
main.main()
	main.go:223 +0xec

goroutine 23 [IO wait]:
internal/poll.runtime_pollWait(0x7f0e41d14d68, 0x72, 0xffffffffffffffff)
	/usr/lib/go/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc00017a918, 0x72, 0xf00, 0xf79, 0xffffffffffffffff)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc00017a900, 0xc000464000, 0xf79, 0xf79, 0x0, 0x0, 0x0)
	/usr/lib/go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc00017a900, 0xc000464000, 0xf79, 0xf79, 0x203000, 0xc000139988, 0x412189)
	/usr/lib/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc00042c000, 0xc000464000, 0xf79, 0xf79, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/net.go:177 +0x69
crypto/tls.(*atLeastReader).Read(0xc0003d80a0, 0xc000464000, 0xf79, 0xf79, 0xc000226000, 0x140, 0xc0001399e0)
	/usr/lib/go/src/crypto/tls/conn.go:761 +0x60
bytes.(*Buffer).ReadFrom(0xc00043c258, 0x8007c0, 0xc0003d80a0, 0x410295, 0x7322c0, 0x773b40)
	/usr/lib/go/src/bytes/buffer.go:207 +0xbd
crypto/tls.(*Conn).readFromUntil(0xc00043c000, 0x800aa0, 0xc00042c000, 0x5, 0xc00042c000, 0xa434c0)
	/usr/lib/go/src/crypto/tls/conn.go:783 +0xf8
crypto/tls.(*Conn).readRecordOrCCS(0xc00043c000, 0x7a3900, 0xc00043c138, 0xc000139d58)
	/usr/lib/go/src/crypto/tls/conn.go:590 +0x125
crypto/tls.(*Conn).readRecord(...)
	/usr/lib/go/src/crypto/tls/conn.go:558
crypto/tls.(*Conn).Read(0xc00043c000, 0xc0003a0000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go/src/crypto/tls/conn.go:1236 +0x137
bufio.(*Reader).Read(0xc00042a720, 0xc0003c4b98, 0x9, 0x9, 0x40cf84, 0xc00042a780, 0xc000139d58)
	/usr/lib/go/src/bufio/bufio.go:223 +0x23e
io.ReadAtLeast(0x8006a0, 0xc00042a720, 0xc0003c4b98, 0x9, 0x9, 0x9, 0x800900, 0xc0003891a0, 0xc000048040)
	/usr/lib/go/src/io/io.go:310 +0x88
io.ReadFull(...)
	/usr/lib/go/src/io/io.go:329
net/http.http2readFrameHeader(0xc0003c4b98, 0x9, 0x9, 0x8006a0, 0xc00042a720, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/http/h2_bundle.go:1476 +0x88
net/http.(*http2Framer).ReadFrame(0xc0003c4b60, 0xc000100210, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/http/h2_bundle.go:1734 +0xa1
net/http.(*http2clientConnReadLoop).run(0xc000139fb8, 0x7a3340, 0xc000034fb8)
	/usr/lib/go/src/net/http/h2_bundle.go:8102 +0x8f
net/http.(*http2ClientConn).readLoop(0xc000406c00)
	/usr/lib/go/src/net/http/h2_bundle.go:8030 +0x76
created by net/http.(*http2Transport).newClientConn
	/usr/lib/go/src/net/http/h2_bundle.go:7093 +0x637

rax    0xca
rbx    0xa3ce00
rcx    0x460043
rdx    0x0
rdi    0xa3cf48
rsi    0x80
rbp    0x7fff5b647620
rsp    0x7fff5b6475d8
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0x30
r13    0x11
r14    0x7f6d64
r15    0x0
rip    0x460041
rflags 0x286
cs     0x33
fs     0x0
gs     0x0

```

**Comment by parkerlreed** [comment]
Yes... ^\ is a force quit. That works for any program. You are forcing the program to segfault

**Comment by Porkepix** [comment]
Mmmmh, didn't know about this. However this isn't the backspace key on the `fr-oss` layout.

And even if that's force quit, maybe it shouldn't throw a big stack trace?

**Comment by Morganamilo** [comment]
Sigkill and segfaults are different things.

**Comment by parkerlreed** [comment]
Aye. I mentioned that since SIGKILL usually produces a core dump as if the program segfaulted.

**Comment by Jguer** [comment]
ctrl-shift-4 on fr-oss layout sends a SIGQUIT (^\ , check `stty -a`, also matches your prompt `==> ^\SIGQUIT: quit` ).

Here is how go handles signals by default: https://golang.org/pkg/os/signal/
and the relevant passages:

```
The SIGQUIT signal is sent when the user at the controlling terminal presses the quit character, which by default is ^\ (Control-Backslash). In general you can cause a program to simply exit by pressing ^C, and you can cause it to exit with a stack dump by pressing ^\. 
``` 

```
By default, a synchronous signal is converted into a run-time panic. A SIGHUP, SIGINT, or SIGTERM signal causes the program to exit. A SIGQUIT, SIGILL, SIGTRAP, SIGABRT, SIGSTKFLT, SIGEMT, or SIGSYS signal causes the program to exit with a stack dump.
```

This is intended golang behaviour, `SIGINT` is the least brute way of stopping the execution, although yay does not catch any signals, pacman does handle them https://git.archlinux.org/pacman.git/tree/src/pacman/sighandler.c.

I don't consider this a bug or behaviour to change
