### ISSUE TITLE
gendb fails with index out of range

### ISSUE THREAD

**Issue by bemeurer** [Jguer/yay#99]
I'm moving from pacaur to yay, since the former has been deprecated. Since I have a lot of `-git` packaged I ran `yay --gendb` first thing after installing it, however yay got a runtime error and crashed. Here's the output
```
$ yay --gendb
==> Installing 2048-rs
==> Installing aerc-git
==> Installing aic94xx-firmware
==> Installing alacritty-git
==> Installing android-platform
==> Installing android-sdk
==> Installing android-sdk-build-tools
==> Installing android-sdk-platform-tools
==> Installing android-studio
==> Installing antigen-git
==> Installing aria2-fast
==> Installing atom-editor-bin
==> Installing aura-bin
==> Installing auracle-git
==> Installing bashate
==> Installing batify
==> Installing biicode
Error installing biicode : invalid variable:
pkgbase
==> Installing brightnessctl
==> Installing chez-scheme-git
==> Installing chicken-noconflict
==> Installing chromaprint-fftw
==> Installing chrome-gnome-shell-git
==> Installing chromium-widevine
==> Installing clion
panic: runtime error: index out of range
goroutine 1 [running]:
github.com/mikkeloscar/gopkgbuild.parseDependency(0xc42030ee00, 0x0, 0x0, 0x0, 0x0, 0xc4203d8800, 0x4, 0x8, 0x0, 0x0)
        /home/bemeurer/.cache/pacaur/yay/src/.go/src/github.com/mikkeloscar/gopkgbuild/pkgbuild.go:450 +0x989
github.com/mikkeloscar/gopkgbuild.parse(0xc42030ee00, 0x635, 0xc42030ee00, 0xa52420, 0x0)
        /home/bemeurer/.cache/pacaur/yay/src/.go/src/github.com/mikkeloscar/gopkgbuild/pkgbuild.go:300 +0x16f6
github.com/mikkeloscar/gopkgbuild.parsePKGBUILD(0xc42030ee00, 0x635, 0x635, 0x835, 0xc42030ee00)
        /home/bemeurer/.cache/pacaur/yay/src/.go/src/github.com/mikkeloscar/gopkgbuild/pkgbuild.go:209 +0x4d
github.com/mikkeloscar/gopkgbuild.ParseSRCINFO(0xc4202e1500, 0x1f, 0x17, 0x6d8ccd, 0x8)
        /home/bemeurer/.cache/pacaur/yay/src/.go/src/github.com/mikkeloscar/gopkgbuild/pkgbuild.go:204 +0x1b8
main.setupPackageSpace(0xc4204df980, 0x22, 0xc4204df4b8, 0x1, 0x1, 0x25)
        /home/bemeurer/.cache/pacaur/yay/src/yay-2.219/install.go:78 +0x1e3
main.PkgInstall(0xc4204df980, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/bemeurer/.cache/pacaur/yay/src/yay-2.219/install.go:100 +0x116
main.aurInstall(0xc420202000, 0x9a, 0x100, 0x0, 0x0, 0x0, 0xc420216000, 0x6ec)
        /home/bemeurer/.cache/pacaur/yay/src/yay-2.219/install.go:45 +0x20c
main.createDevelDB(0x7ffc062d8c48, 0x7)
        /home/bemeurer/.cache/pacaur/yay/src/yay-2.219/vcs.go:41 +0x9a
main.parser(0x1, 0x6da990, 0xf, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/bemeurer/.cache/pacaur/yay/src/yay-2.219/cmd.go:174 +0x347
main.main()
        /home/bemeurer/.cache/pacaur/yay/src/yay-2.219/cmd.go:221 +0x37
```

**Comment by Morganamilo** [comment]
I think this is another instance of #85 and #70. Its fixed in the master branch if you care to build it yourself. Otherwise you'll have to wait for a new release.

**Comment by samosaara** [comment]
Just in case, it's `go get -u -v github.com/Jguer/yay` to clone master and compile the executable to `$GOPATH/bin/yay`, the default `$GOPATH` is `~/go`

**Comment by bemeurer** [comment]
Doing as @samosaara points out yields the following
```
$ pwd
/home/bemeurer/.go/bin
$ ls
Permissions  Size User     Date Modified Name
.rwxr-xr-x  6.5Mi bemeurer 14 Jan 22:10  yay
$ ./yay --gendb
open /home/bemeurer/.config/yay/yay_vcs.json: no such file or directory
```

**Comment by Morganamilo** [comment]
That's another bug that's fixed in a pr put not yet in master.

If you just create the file manually it should be fine.

**Comment by bemeurer** [comment]
It works now, except for the error on `biicode`
```
==> Installing biicode
Error installing biicode : invalid variable:
pkgbase
```

**Comment by Morganamilo** [comment]
That's a new one. I'll look into it. Thanks for reporting and sorry for all the trouble.

**Comment by bemeurer** [comment]
No worries! I'll close this issue and open a new one for `biicode`
